Qolyester daemon: olsr::set::Neighbor Class Reference
olsr::set::Neighbor Class Reference
#include <neighbors.hh>
Public Types
typedef val_lset_t linkset_t
Public Member Functions
Neighbor (const address_t &maddr, const std::set< ulink_t >::iterator &i, unsigned w)
Neighbor (const This &)
virtual ~Neighbor ()
const address_t & main_addr () const
unsigned willingness () const
const timeval_t & mprsel_time () const
void set_willingness (unsigned w)
bool is_sym () const
bool is_mpr () const
bool is_mprsel () const
bool was_mprsel ()
void set_sym (bool state)
void set_mpr (bool state)
void set_mprsel (const timeval_t &validity)
void unset_mprsel ()
std::pair
< linkset_t::const_iterator,
linkset_t::const_iterator > find_lifaces (const address_t &laddr) const
linkset_t & linkset ()
void insert (const std::set< ulink_t >::iterator &pos)
void erase (const lset_t::iterator &pos)
void erase (const std::set< ulink_t >::iterator &pos)
bool operator< (const This &rhs) const
Static Public Member Functions
static const This & make_key (const address_t &m)
Private Types
typedef Neighbor This
typedef utl::MultiStampable
< 1, address_t > Super
typedef sch::Updatable< Link > ulink_t
typedef utl::Index
< std::multiset, std::set
< ulink_t >, ilinkless > lset_t
typedef utl::Subset
< utl::MultiAdapt< lset_t >
, utl::NoAction< This,
lset_t::iterator >, lset_valid,
This > val_lset_t
Private Member Functions
Neighbor ()
Private Attributes
const address_t m_addr_
lset_t lset_
val_lset_t val_lset_
bool sym_
bool mpr_
timeval_t mprsel_time_
bool was_mprsel_
unsigned willingness_
Static Private Attributes
static Neighbor dummy_for_find_
Friends
class sch::StatePrinter
Classes
struct ilinkless
struct lset_valid
Member Typedef Documentation
typedef Neighbor olsr::set::Neighbor::This [private]
Reimplemented from olsr::utl::MultiStampable< Dim, Key, Compare >.
typedef utl::MultiStampable<1, address_t> olsr::set::Neighbor::Super [private]
typedef sch::Updatable<Link> olsr::set::Neighbor::ulink_t [private]
typedef utl::Index<std::multiset, std::set<ulink_t>, ilinkless> olsr::set::Neighbor::lset_t [private]
typedef utl::Subset<utl::MultiAdapt<lset_t>, utl::NoAction<This, lset_t::iterator>, lset_valid, This> olsr::set::Neighbor::val_lset_t [private]
typedef val_lset_t olsr::set::Neighbor::linkset_t
Constructor & Destructor Documentation
olsr::set::Neighbor::Neighbor () [inline, explicit, private]
olsr::set::Neighbor::Neighbor (const address_t & maddr, const std::set< ulink_t >::iterator & i, unsigned w) [inline]
References lset_.
olsr::set::Neighbor::Neighbor (const This & other) [inline]
virtual olsr::set::Neighbor::~Neighbor () [inline, virtual]
Member Function Documentation
const address_t& olsr::set::Neighbor::main_addr () const [inline]
References m_addr_.
Referenced by olsr::alg::mprselection().
unsigned olsr::set::Neighbor::willingness () const [inline]
References willingness_.
Referenced by olsr::alg::mprselection().
const timeval_t& olsr::set::Neighbor::mprsel_time () const [inline]
References mprsel_time_.
void olsr::set::Neighbor::set_willingness (unsigned w) [inline]
References willingness_.
bool olsr::set::Neighbor::is_sym () const [inline]
References sym_.
bool olsr::set::Neighbor::is_mpr () const [inline]
References mpr_.
bool olsr::set::Neighbor::is_mprsel () const [inline]
References olsr::utl::TimeVal::is_past(), and mprsel_time_.
Referenced by set_mprsel().
bool olsr::set::Neighbor::was_mprsel () [inline]
References was_mprsel_.
void olsr::set::Neighbor::set_sym (bool state) [inline]
References sym_.
void olsr::set::Neighbor::set_mpr (bool state) [inline]
References mpr_.
void olsr::set::Neighbor::set_mprsel (const timeval_t & validity) [inline]
References olsr::utl::TimeVal::in(), is_mprsel(), mprsel_time_, and was_mprsel_.
void olsr::set::Neighbor::unset_mprsel () [inline]
References mprsel_time_, and olsr::utl::TimeVal::now().
std::pair< Neighbor::linkset_t::const_iterator, Neighbor::linkset_t::const_iterator > olsr::set::Neighbor::find_lifaces (const address_t & laddr) const [inline]
References olsr::set::Link::make_key_local(), and val_lset_.
linkset_t& olsr::set::Neighbor::linkset () [inline]
References val_lset_.
void olsr::set::Neighbor::insert (const std::set< ulink_t >::iterator & pos) [inline]
References lset_.
void olsr::set::Neighbor::erase (const lset_t::iterator & pos) [inline]
References lset_.
void olsr::set::Neighbor::erase (const std::set< ulink_t >::iterator & pos) [inline]
References lset_.
bool olsr::set::Neighbor::operator< (const This & rhs) const [inline]
References m_addr_.
const Neighbor & olsr::set::Neighbor::make_key (const address_t & m) [inline, static]
References dummy_for_find_, and m_addr_.
Referenced by olsr::msg::HELLOMessage::dump(), olsr::set::TopologySet::erase(), olsr::set::TwoHopNeighborSet::erase(), olsr::set::CoherenceProxy::erase(), olsr::msg::Message::forward(), olsr::set::TwoHopNeighborSet::insert(), olsr::alg::mprselection(), and olsr::set::CoherenceProxy::update_state().
Friends And Related Function Documentation
friend class sch::StatePrinter [friend]
Member Data Documentation
const address_t olsr::set::Neighbor::m_addr_ [private]
Referenced by main_addr(), make_key(), and operator<().
lset_t olsr::set::Neighbor::lset_ [private]
Referenced by erase(), insert(), and Neighbor().
val_lset_t olsr::set::Neighbor::val_lset_ [private]
Referenced by find_lifaces(), and linkset().
bool olsr::set::Neighbor::sym_ [private]
Referenced by is_sym(), and set_sym().
bool olsr::set::Neighbor::mpr_ [private]
Referenced by is_mpr(), and set_mpr().
timeval_t olsr::set::Neighbor::mprsel_time_ [private]
Referenced by is_mprsel(), mprsel_time(), set_mprsel(), and unset_mprsel().
bool olsr::set::Neighbor::was_mprsel_ [private]
Referenced by set_mprsel(), and was_mprsel().
unsigned olsr::set::Neighbor::willingness_ [private]
Referenced by set_willingness(), and willingness().
Neighbor olsr::set::Neighbor::dummy_for_find_ [static, private]
Referenced by make_key().
The documentation for this class was generated from the following files:
neighbors.hh
neighbors.hxx