Qolyester daemon: olsr::set::Link Class Reference
olsr::set::Link Class Reference
#include <neighbors.hh>
Public Member Functions
Link (const address_t &l, const address_t &r, const address_t &m, const timeval_t &v)
Link (const This &other)
virtual ~Link ()
void set_asymtime (const timeval_t &t)
void set_symtime (const timeval_t &t)
void set_time (const timeval_t &t)
const address_t & local_addr () const
const address_t & remote_addr () const
const address_t & main_addr () const
const timeval_t & asymtime () const
const timeval_t & symtime () const
const timeval_t & time () const
bool is_valid () const
bool is_sym () const
bool was_sym () const
void set_was_sym (bool ws)
bool operator< (const This &rhs) const
Static Public Member Functions
static const This & make_key (const address_t &local, const address_t &remote)
static const This & make_key_local (const address_t &local)
Private Types
typedef Link This
typedef utl::MultiStampable
< 1, address_t > Super
Private Member Functions
Link ()
Private Attributes
const address_t l_addr_
const address_t r_addr_
const address_t m_addr_
timeval_t asymtime_
timeval_t symtime_
timeval_t time_
bool was_sym_
Static Private Attributes
static This dummy_for_find_
Friends
class sch::StatePrinter
Member Typedef Documentation
typedef Link olsr::set::Link::This [private]
Reimplemented from olsr::utl::MultiStampable< Dim, Key, Compare >.
typedef utl::MultiStampable<1, address_t> olsr::set::Link::Super [private]
Constructor & Destructor Documentation
olsr::set::Link::Link () [explicit, private]
olsr::set::Link::Link (const address_t & l, const address_t & r, const address_t & m, const timeval_t & v) [inline]
olsr::set::Link::Link (const This & other) [inline]
virtual olsr::set::Link::~Link () [inline, virtual]
Member Function Documentation
void olsr::set::Link::set_asymtime (const timeval_t & t) [inline]
References asymtime_.
Referenced by olsr::set::CoherenceProxy::insert_link().
void olsr::set::Link::set_symtime (const timeval_t & t) [inline]
References symtime_.
Referenced by olsr::set::CoherenceProxy::insert_link().
void olsr::set::Link::set_time (const timeval_t & t) [inline]
References time_.
Referenced by olsr::set::CoherenceProxy::insert_link().
const address_t& olsr::set::Link::local_addr () const [inline]
References l_addr_.
const address_t& olsr::set::Link::remote_addr () const [inline]
References r_addr_.
const address_t& olsr::set::Link::main_addr () const [inline]
References m_addr_.
const timeval_t& olsr::set::Link::asymtime () const [inline]
References asymtime_.
Referenced by olsr::set::CoherenceProxy::insert_link(), and olsr::set::upd::LinkUpdater::min_time().
const timeval_t& olsr::set::Link::symtime () const [inline]
References symtime_.
Referenced by olsr::set::upd::LinkUpdater::min_time().
const timeval_t& olsr::set::Link::time () const [inline]
References time_.
Referenced by olsr::set::CoherenceProxy::insert_link(), and olsr::set::upd::LinkUpdater::min_time().
bool olsr::set::Link::is_valid () const [inline]
References olsr::utl::TimeVal::is_past(), and time_.
bool olsr::set::Link::is_sym () const [inline]
References olsr::utl::TimeVal::is_past(), and symtime_.
bool olsr::set::Link::was_sym () const [inline]
References was_sym_.
void olsr::set::Link::set_was_sym (bool ws) [inline]
References was_sym_.
bool olsr::set::Link::operator< (const This & rhs) const [inline]
References l_addr_, and r_addr_.
const Link & olsr::set::Link::make_key (const address_t & local, const address_t & remote) [inline, static]
References dummy_for_find_, l_addr_, and r_addr_.
Referenced by olsr::msg::Message::forward(), olsr::msg::TCMessage::parse(), olsr::pkt::Packet::parse(), olsr::msg::MIDMessage::parse(), and olsr::msg::HNAMessage::parse().
const Link & olsr::set::Link::make_key_local (const address_t & local) [inline, static]
References dummy_for_find_, and l_addr_.
Referenced by olsr::set::Neighbor::find_lifaces().
Friends And Related Function Documentation
friend class sch::StatePrinter [friend]
Member Data Documentation
const address_t olsr::set::Link::l_addr_ [private]
Referenced by local_addr(), make_key(), make_key_local(), and operator<().
const address_t olsr::set::Link::r_addr_ [private]
Referenced by make_key(), operator<(), and remote_addr().
const address_t olsr::set::Link::m_addr_ [private]
Referenced by main_addr().
timeval_t olsr::set::Link::asymtime_ [private]
Referenced by asymtime(), and set_asymtime().
timeval_t olsr::set::Link::symtime_ [private]
Referenced by is_sym(), set_symtime(), and symtime().
timeval_t olsr::set::Link::time_ [private]
Referenced by is_valid(), set_time(), and time().
bool olsr::set::Link::was_sym_ [private]
Referenced by set_was_sym(), and was_sym().
This olsr::set::Link::dummy_for_find_ [static, private]
Referenced by make_key(), and make_key_local().
The documentation for this class was generated from the following files:
neighbors.hh
neighbors.hxx