Qolyester daemon: olsr::utl::Data Struct Reference
olsr::utl::Data Struct Reference
#include <data.hh>
Public Member Functions
Data ()
Data (::size_t size)
u_int8_t * raw ()
Access the raw data.
Constructor & Destructor Documentation
olsr::utl::Data::Data () [inline]
olsr::utl::Data::Data (::size_t size) [inline, explicit]
Member Function Documentation
u_int8_t * olsr::utl::Data::raw () [inline]
Access the raw data.
References olsr::utl::internal::shared_data::buffer, olsr::utl::Data_< Self >::data_, and olsr::utl::Data_< Self >::offset_.
Referenced by olsr::msg::TCMessage::dump(), olsr::msg::MIDMessage::dump(), olsr::msg::HNAMessage::dump(), olsr::msg::HELLOMessage::dump(), olsr::msg::Message::forward(), olsr::pkt::Packet::Packet(), olsr::pkt::Packet::parse(), olsr::msg::Message::parse(), olsr::sys::UnixSocket::receive(), and olsr::sys::Socket::receive().
The documentation for this struct was generated from the following files:
data.hh
data.hxx