Qolyester daemon: olsr::msg::HELLOMessage Class Reference
olsr::msg::HELLOMessage Class Reference
The HELLO message class.
#include <hello.hh>
Public Member Functions
virtual ~HELLOMessage ()
virtual bool dump (utl::Data &, const address_t &) const
Static Public Member Functions
static void parse (const utl::ConstData &, const Message::header &)
Static Protected Attributes
static const ::size_t min_length = sizeof (raw)
Minimum length of HELLO message.
Classes
struct linksetraw
Convenience structure of header of link set portion of HELLO message.
struct raw
Convenience structure of HELLO message header.
Detailed Description
The HELLO message class.
Constructor & Destructor Documentation
virtual olsr::msg::HELLOMessage::~HELLOMessage () [inline, virtual]
The destructor
Member Function Documentation
bool olsr::msg::HELLOMessage::dump (utl::Data & d, const address_t & interface) const [inline, virtual]
The message dumper
d Destination data buffer
interface Source interface address of the packet
Returns:
true if the message has to be fragmented
The HELLO message is generated on demand and the returned flag indicates whether the message has to be regenerated to avoid remote data expiration.
Implements olsr::msg::Message.
References olsr::msg::Message::raw::addr, ADDRESS_SIZE, ASYM_LINK, olsr::cproxy, olsr::msg::Message::raw::data, olsr::debug, olsr::utl::deindent(), olsr::do_dump_hello, olsr::utl::down(), olsr::net::IPv6Address::dump(), olsr::dump_hello, olsr::cst::hello_interval, olsr::set::CoherenceProxy::hello_linkset(), HELLO_MESSAGE, olsr::msg::Message::raw::hopcount, olsr::msg::HELLOMessage::raw::htime, olsr::utl::TimeVal::in(), indent, LOST_LINK, olsr::main_addr, olsr::set::Neighbor::make_key(), min_length, olsr::msg::Message::min_length, MPR_NEIGH, olsr::cst::neighb_hold_time, olsr::set::CoherenceProxy::neighborset(), NOT_NEIGH, olsr::utl::TimeVal::now(), PROC_XX_SET, olsr::utl::Data::raw(), olsr::cst::refresh_interval, olsr::msg::HELLOMessage::raw::reserved, olsr::msg::Message::raw::seqnum, olsr::msg::Message::seqnum, olsr::msg::Message::raw::size, olsr::utl::Data_< Self >::size(), SYM_LINK, SYM_NEIGH, olsr::msg::Message::raw::ttl, olsr::msg::Message::raw::type, UNSPEC_LINK, olsr::utl::up(), olsr::msg::Message::raw::vtime, olsr::willingness, and olsr::msg::HELLOMessage::raw::willingness.
void olsr::msg::HELLOMessage::parse (const utl::ConstData & d, const Message::header & mh) [inline, static]
The message parser
d Message data to parse
mh Message header
References ADDRESS_SIZE, ASYM_LINK, olsr::cproxy, olsr::do_dump_hello, olsr::dump_hello, olsr::set::TwoHopNeighborSet::erase(), olsr::msg::HELLOMessage::raw::htime, olsr::set::TwoHopNeighborSet::insert(), olsr::set::CoherenceProxy::insert_link(), LOST_LINK, olsr::main_addr, olsr::alg::main_addr_of(), olsr::set::TwoHopNeighbor::make_key(), MPR_NEIGH, olsr::msg::Message::header::mseqnum, NOT_NEIGH, olsr::msg::Message::header::originator, olsr::msg::Message::header::pseqnum, olsr::utl::Data_< Self >::raw(), olsr::msg::Message::header::receiver, olsr::msg::Message::header::sender, olsr::set::CoherenceProxy::set_mprsel(), olsr::utl::Data_< Self >::size(), SYM_LINK, SYM_NEIGH, olsr::thn_set, olsr::set::CoherenceProxy::unset_mprsel(), UNSPEC_LINK, olsr::msg::Message::header::validity, and olsr::msg::HELLOMessage::raw::willingness.
Referenced by olsr::msg::Message::parse().
Member Data Documentation
const ::size_t olsr::msg::HELLOMessage::min_length = sizeof (raw) [static, protected]
Minimum length of HELLO message.
Reimplemented from olsr::msg::Message.
Referenced by dump().
The documentation for this class was generated from the following files:
hello.hh
hello.hxx