Qolyester daemon: olsr::sch::Event Class Reference
olsr::sch::Event Class Reference
Abstract event class.
#include <scheduler.hh>
Public Member Functions
Event ()
virtual ~Event ()
virtual void handle ()=0
null_t name () const
Detailed Description
Abstract event class.
Constructor & Destructor Documentation
olsr::sch::Event::Event () [inline]
Event constructor.
virtual olsr::sch::Event::~Event () [inline, virtual]
Member Function Documentation
virtual void olsr::sch::Event::handle () [pure virtual]
Virtual handling method.
Implemented in olsr::sch::MessageSender< M >, olsr::sch::MessageSender< msg::TCMessage >, olsr::sch::MessageForwarder, olsr::sch::StatePrinter, olsr::sch::PacketSender, olsr::sch::PacketReceiver, olsr::sch::UpdateEvent< F >, olsr::sch::PeriodicEvent_< I >, and olsr::sch::PeriodicEvent_< olsr::sch::internal::JitterIncrement >.
Referenced by olsr::sch::Scheduler::handle_ioevents(), and olsr::sch::Scheduler::handle_tevents().
null_t olsr::sch::Event::name () const [inline]
Referenced by olsr::sch::Scheduler::erase(), olsr::net::RealInterface::erase_event(), olsr::sch::Scheduler::handle_ioevents(), olsr::sch::Scheduler::handle_tevents(), olsr::sch::Scheduler::insert(), and olsr::net::RealInterface::insert_event().
The documentation for this class was generated from the following files:
scheduler.hh
scheduler.hxx