Qolyester daemon: olsr::utl::DerefIterator< Iter > Class Template Reference
olsr::utl::DerefIterator< Iter > Class Template Reference
#include <iterator.hh>
Public Member Functions
DerefIterator ()
DerefIterator (const This &other)
Ref operator* () const
Ptr operator-> () const
This & operator++ ()
This operator++ (int)
const Super & deref_super () const
Super & deref_super ()
Static Public Member Functions
static This build (const Super &other)
Private Types
typedef DerefIterator This
typedef Iter Super
typedef std::iterator_traits
< Iter >::value_type Elem
typedef std::iterator_traits
< Elem >::value_type Value
typedef std::iterator_traits
< Elem >::reference Ref
typedef std::iterator_traits
< Elem >::pointer Ptr
template<class Iter>
class olsr::utl::DerefIterator< Iter >
Member Typedef Documentation
template<class Iter> typedef DerefIterator olsr::utl::DerefIterator< Iter >::This [private]
template<class Iter> typedef Iter olsr::utl::DerefIterator< Iter >::Super [private]
template<class Iter> typedef std::iterator_traits<Iter>::value_type olsr::utl::DerefIterator< Iter >::Elem [private]
template<class Iter> typedef std::iterator_traits<Elem>::value_type olsr::utl::DerefIterator< Iter >::Value [private]
template<class Iter> typedef std::iterator_traits<Elem>::reference olsr::utl::DerefIterator< Iter >::Ref [private]
template<class Iter> typedef std::iterator_traits<Elem>::pointer olsr::utl::DerefIterator< Iter >::Ptr [private]
Constructor & Destructor Documentation
template<class Iter> olsr::utl::DerefIterator< Iter >::DerefIterator () [inline]
template<class Iter> olsr::utl::DerefIterator< Iter >::DerefIterator (const This & other) [inline]
Member Function Documentation
template<class Iter> Ref olsr::utl::DerefIterator< Iter >::operator* () const [inline]
template<class Iter> Ptr olsr::utl::DerefIterator< Iter >::operator-> () const [inline]
template<class Iter> This& olsr::utl::DerefIterator< Iter >::operator++ () [inline]
template<class Iter> This olsr::utl::DerefIterator< Iter >::operator++ (int) [inline]
References olsr::utl::DerefIterator< Iter >::build().
template<class Iter> const Super& olsr::utl::DerefIterator< Iter >::deref_super () const [inline]
template<class Iter> Super& olsr::utl::DerefIterator< Iter >::deref_super () [inline]
template<class Iter> static This olsr::utl::DerefIterator< Iter >::build (const Super & other) [inline, static]
Referenced by olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::begin(), olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::end(), olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::find(), and olsr::utl::DerefIterator< Iter >::operator++().
The documentation for this class was generated from the following file:
iterator.hh