Qolyester daemon: olsr::utl::MultiStampable< 1, Key, Compare > Class Template Reference
olsr::utl::MultiStampable< 1, Key, Compare > Class Template Reference
#include <stampable.hh>
Public Member Functions
void set_stamp (const Key &k, const TimeVal &now=TimeVal::now())
void set_stamp (unsigned d, const Key &k, const TimeVal &now=TimeVal::now())
void remove_stamp (const Key &k)
void remove_stamp (unsigned d, const Key &k)
const TimeVal stamp (const Key &k) const
const TimeVal stamp (unsigned d, const Key &k) const
bool expired (const Key &k, const TimeVal &period, const TimeVal &now=TimeVal::now()) const
bool expired (unsigned d, const Key &k, const TimeVal &period, const TimeVal &now=TimeVal::now()) const
bool less (const Key &k, const This &rhs) const
bool less (unsigned d, const Key &k, const This &rhs) const
Protected Member Functions
MultiStampable ()
Private Types
typedef MultiStampable< 1, Key,
Compare > This
typedef std::map< Key, TimeVal > stampset_t
Private Attributes
stampset_t _stampset
template<class Key, class Compare>
class olsr::utl::MultiStampable< 1, Key, Compare >
Member Typedef Documentation
template<class Key, class Compare> typedef MultiStampable<1, Key, Compare> olsr::utl::MultiStampable< 1, Key, Compare >::This [private]
template<class Key, class Compare> typedef std::map<Key, TimeVal> olsr::utl::MultiStampable< 1, Key, Compare >::stampset_t [private]
Constructor & Destructor Documentation
template<class Key, class Compare> olsr::utl::MultiStampable< 1, Key, Compare >::MultiStampable () [inline, protected]
Member Function Documentation
template<class Key, class Compare> void olsr::utl::MultiStampable< 1, Key, Compare >::set_stamp (const Key & k, const TimeVal & now = TimeVal::now()) [inline]
References olsr::utl::MultiStampable< Dim, Key, Compare >::_stampset.
template<class Key, class Compare> void olsr::utl::MultiStampable< 1, Key, Compare >::set_stamp (unsigned d, const Key & k, const TimeVal & now = TimeVal::now()) [inline]
References olsr::utl::MultiStampable< Dim, Key, Compare >::set_stamp().
template<class Key, class Compare> void olsr::utl::MultiStampable< 1, Key, Compare >::remove_stamp (const Key & k) [inline]
References olsr::utl::MultiStampable< Dim, Key, Compare >::_stampset.
template<class Key, class Compare> void olsr::utl::MultiStampable< 1, Key, Compare >::remove_stamp (unsigned d, const Key & k) [inline]
References olsr::utl::MultiStampable< Dim, Key, Compare >::remove_stamp().
template<class Key, class Compare> const TimeVal olsr::utl::MultiStampable< 1, Key, Compare >::stamp (const Key & k) const [inline]
References olsr::utl::MultiStampable< Dim, Key, Compare >::_stampset.
Referenced by less().
template<class Key, class Compare> const TimeVal olsr::utl::MultiStampable< 1, Key, Compare >::stamp (unsigned d, const Key & k) const [inline]
References olsr::utl::MultiStampable< Dim, Key, Compare >::stamp().
template<class Key, class Compare> bool olsr::utl::MultiStampable< 1, Key, Compare >::expired (const Key & k, const TimeVal & period, const TimeVal & now = TimeVal::now()) const [inline]
References olsr::utl::MultiStampable< Dim, Key, Compare >::stamp().
template<class Key, class Compare> bool olsr::utl::MultiStampable< 1, Key, Compare >::expired (unsigned d, const Key & k, const TimeVal & period, const TimeVal & now = TimeVal::now()) const [inline]
References olsr::utl::MultiStampable< Dim, Key, Compare >::expired().
template<class Key, class Compare> bool olsr::utl::MultiStampable< 1, Key, Compare >::less (const Key & k, const This & rhs) const [inline]
References stamp(), and olsr::utl::MultiStampable< Dim, Key, Compare >::stamp().
template<class Key, class Compare> bool olsr::utl::MultiStampable< 1, Key, Compare >::less (unsigned d, const Key & k, const This & rhs) const [inline]
References olsr::utl::MultiStampable< Dim, Key, Compare >::less().
Member Data Documentation
template<class Key, class Compare> stampset_t olsr::utl::MultiStampable< 1, Key, Compare >::_stampset [private]
The documentation for this class was generated from the following files:
stampable.hh
stampable.hxx