Qolyester daemon: olsr::set::HNASet Class Reference
olsr::set::HNASet Class Reference
#include <hna.hh>
Public Types
typedef val_hset_t hnaset_t
Public Member Functions
hnaset_t & hnaset ()
HNASet ()
void insert (const HNAEntry &x)
void erase (const hset_t::iterator &pos)
Private Types
typedef HNASet This
typedef sch::Updatable< HNAEntry > elem_t
typedef std::set< elem_t > hset_t
typedef sch::upd::SetEraser
< This, hset_t::iterator > eraser_t
typedef sch::UpdateEvent
< eraser_t > updater_t
typedef utl::Subset< hset_t,
utl::NoAction< This,
hset_t::iterator >
, utl::DefaultPredicate< This,
hset_t::iterator >, This > val_hset_t
Private Attributes
hset_t hset_
hnaset_t hnaset_
Friends
class sch::StatePrinter
Member Typedef Documentation
typedef HNASet olsr::set::HNASet::This [private]
typedef sch::Updatable<HNAEntry> olsr::set::HNASet::elem_t [private]
typedef std::set<elem_t> olsr::set::HNASet::hset_t [private]
typedef sch::upd::SetEraser<This, hset_t::iterator> olsr::set::HNASet::eraser_t [private]
typedef sch::UpdateEvent<eraser_t> olsr::set::HNASet::updater_t [private]
typedef utl::Subset<hset_t, utl::NoAction<This, hset_t::iterator>, utl::DefaultPredicate<This, hset_t::iterator>, This> olsr::set::HNASet::val_hset_t [private]
typedef val_hset_t olsr::set::HNASet::hnaset_t
Constructor & Destructor Documentation
olsr::set::HNASet::HNASet () [inline]
Member Function Documentation
hnaset_t& olsr::set::HNASet::hnaset () [inline]
References hnaset_.
Referenced by olsr::alg::compute_routes().
void olsr::set::HNASet::insert (const HNAEntry & x) [inline]
References olsr::sch::Scheduler::erase(), hset_, olsr::sch::Scheduler::insert(), olsr::routes_recomp, olsr::scheduler, olsr::utl::Mark::set_mark(), olsr::sch::TimedEvent::set_next(), and olsr::set::HNAEntry::time().
Referenced by olsr::msg::HNAMessage::parse().
void olsr::set::HNASet::erase (const hset_t::iterator & pos) [inline]
References olsr::sch::Scheduler::destroy(), hset_, olsr::routes_recomp, olsr::scheduler, and olsr::utl::Mark::set_mark().
Friends And Related Function Documentation
friend class sch::StatePrinter [friend]
Member Data Documentation
hset_t olsr::set::HNASet::hset_ [private]
Referenced by erase(), olsr::sch::StatePrinter::handle(), and insert().
hnaset_t olsr::set::HNASet::hnaset_ [private]
Referenced by hnaset().
The documentation for this class was generated from the following files:
set/hna.hh
set/hna.hxx