Qolyester daemon: olsr::utl::Mark Class Reference
olsr::utl::Mark Class Reference
#include <mark.hh>
Public Member Functions
Mark ()
void reset ()
bool mark () const
void set_mark ()
Private Types
typedef Mark This
Private Attributes
bool _mark
Member Typedef Documentation
typedef Mark olsr::utl::Mark::This [private]
Constructor & Destructor Documentation
olsr::utl::Mark::Mark () [inline]
Member Function Documentation
void olsr::utl::Mark::reset () [inline]
References _mark.
Referenced by olsr::sch::QolyesterLoopHandler::operator()().
bool olsr::utl::Mark::mark () const [inline]
References _mark.
Referenced by olsr::sch::LoopHandler::operator()(), and olsr::sch::QolyesterLoopHandler::operator()().
void olsr::utl::Mark::set_mark () [inline]
References _mark.
Referenced by olsr::set::TopologySet::erase(), olsr::set::TwoHopNeighborSet::erase(), olsr::set::MIDSet::erase(), olsr::set::HNASet::erase(), olsr::set::TopologySet::insert(), olsr::set::TwoHopNeighborSet::insert(), olsr::set::MIDSet::insert(), olsr::set::HNASet::insert(), olsr::sch::int_handler(), olsr::alg::mprselection(), olsr::gra::AdjGraph::remove_node(), olsr::set::CoherenceProxy::set_mpr(), olsr::set::CoherenceProxy::set_mprsel(), olsr::set::CoherenceProxy::set_sym(), olsr::set::CoherenceProxy::set_willingness(), olsr::sch::term_handler(), olsr::set::CoherenceProxy::unset_mpr(), olsr::set::CoherenceProxy::unset_mprsel(), olsr::set::CoherenceProxy::unset_sym(), and olsr::set::CoherenceProxy::update_state().
Member Data Documentation
bool olsr::utl::Mark::_mark [private]
Referenced by mark(), reset(), and set_mark().
The documentation for this class was generated from the following file:
mark.hh