Qolyester daemon: olsr::sys::netlink::InitVisitor Class Reference
olsr::sys::netlink::InitVisitor Class Reference
#include <interfacedesc.hh>
Public Member Functions
InitVisitor (std::string &name, unsigned &index, unsigned &mtu, addrs_t &addrs)
virtual void visit (const NLError &e)
virtual void visit (const NLNewLink &e)
virtual void visit (const NLLinkAttrName &e)
virtual void visit (const NLLinkAttrMTU &e)
virtual void visit (const NLNewAddr &e)
virtual void visit (const NLAddrAttrAddress &e)
virtual void visit (const NLAddrAttrBroadcast &e)
Package Types
typedef std::set< addr_t > addrs_t
Package Attributes
__pad0__:InterfaceAddress addr_t
Private Types
typedef InitVisitor This
Private Attributes
std::string & _name
unsigned & _index
unsigned & _mtu
addrs_t & _addrs
unsigned _prefix
unsigned char _scope
address_t _address
address_t _broadcast
Member Typedef Documentation
typedef InitVisitor olsr::sys::netlink::InitVisitor::This [private]
typedef std::set<addr_t> olsr::sys::netlink::InitVisitor::addrs_t [package]
Constructor & Destructor Documentation
olsr::sys::netlink::InitVisitor::InitVisitor (std::string & name, unsigned & index, unsigned & mtu, addrs_t & addrs)
Member Function Documentation
void olsr::sys::netlink::InitVisitor::visit (const NLError & e) [virtual]
References olsr::sys::netlink::NLError::get_errno().
void olsr::sys::netlink::InitVisitor::visit (const NLNewLink & e) [virtual]
References _index, _name, olsr::sys::netlink::NLNewLink::attrs(), and olsr::sys::netlink::NLNewLink::index().
void olsr::sys::netlink::InitVisitor::visit (const NLLinkAttrName & e) [virtual]
References _name, and olsr::sys::netlink::NLLinkAttrName::name().
void olsr::sys::netlink::InitVisitor::visit (const NLLinkAttrMTU & e) [virtual]
References _mtu, and olsr::sys::netlink::NLLinkAttrMTU::mtu().
void olsr::sys::netlink::InitVisitor::visit (const NLNewAddr & e) [virtual]
References _address, _addrs, _broadcast, _index, _prefix, _scope, olsr::sys::netlink::NLNewAddr::attrs(), olsr::net::IPv6Address::family, olsr::sys::netlink::NLNewAddr::family(), olsr::sys::netlink::NLNewAddr::index(), olsr::sys::netlink::NLNewAddr::prefixlen(), and olsr::sys::netlink::NLNewAddr::scope().
void olsr::sys::netlink::InitVisitor::visit (const NLAddrAttrAddress & e) [virtual]
References _address, olsr::sys::netlink::NLAddrAttrAddress::bytes(), and olsr::sys::netlink::NLAddrAttrAddress::length().
void olsr::sys::netlink::InitVisitor::visit (const NLAddrAttrBroadcast & e) [virtual]
References _broadcast, olsr::sys::netlink::NLAddrAttrBroadcast::bytes(), and olsr::sys::netlink::NLAddrAttrBroadcast::length().
Member Data Documentation
olsr::sys::netlink::InitVisitor::__pad0__ [package]
std::string& olsr::sys::netlink::InitVisitor::_name [private]
Referenced by visit().
unsigned& olsr::sys::netlink::InitVisitor::_index [private]
Referenced by visit().
unsigned& olsr::sys::netlink::InitVisitor::_mtu [private]
Referenced by visit().
addrs_t& olsr::sys::netlink::InitVisitor::_addrs [private]
Referenced by visit().
unsigned olsr::sys::netlink::InitVisitor::_prefix [private]
Referenced by visit().
unsigned char olsr::sys::netlink::InitVisitor::_scope [private]
Referenced by visit().
address_t olsr::sys::netlink::InitVisitor::_address [private]
Referenced by visit().
address_t olsr::sys::netlink::InitVisitor::_broadcast [private]
Referenced by visit().
The documentation for this class was generated from the following files:
linux/interfacedesc.hh
linux/interfacedesc.hxx