Qolyester daemon: olsr::msg::HNAMessage Class Reference
olsr::msg::HNAMessage Class Reference
HNA message declaration.
#include <hna.hh>
Public Member Functions
HNAMessage ()
HNAMessage (const utl::Data &d)
virtual ~HNAMessage ()
virtual bool dump (utl::Data &, const address_t &) const
Static Public Member Functions
static void parse (const utl::ConstData &, const Message::header &)
Static Public Attributes
static const ::size_t min_length = ADDRESS_SIZE * 2
Minimum lenght of HNA message.
Private Types
typedef HNAMessage This
typedef Message Super
Private Attributes
utl::Data _data
The message data buffer.
Detailed Description
HNA message declaration.
Member Typedef Documentation
typedef HNAMessage olsr::msg::HNAMessage::This [private]
typedef Message olsr::msg::HNAMessage::Super [private]
Constructor & Destructor Documentation
olsr::msg::HNAMessage::HNAMessage () [inline]
The default constructor
olsr::msg::HNAMessage::HNAMessage (const utl::Data & d) [inline]
The constructor
d Message data buffer
virtual olsr::msg::HNAMessage::~HNAMessage () [inline, virtual]
The destructor
Member Function Documentation
bool olsr::msg::HNAMessage::dump (utl::Data & d, const address_t & interface) const [inline, virtual]
The dumping method
d Destination data buffer
interface Source interface address of the packet
Returns:
true if the message has to be fragmented
Implements olsr::msg::Message.
References _data, olsr::msg::Message::raw::addr, ADDRESS_SIZE, olsr::utl::Data_< Self >::dump(), olsr::net::IPv6Address::dump(), olsr::dump_hna, olsr::set::GateSet::empty(), olsr::utl::Data_< Self >::empty(), olsr::gate_set, olsr::set::GateSet::hna_gset(), HNA_MESSAGE, olsr::msg::Message::raw::hopcount, olsr::utl::TimeVal::in(), olsr::main_addr, min_length, olsr::msg::Message::min_length, olsr::utl::TimeVal::now(), olsr::utl::Data::raw(), olsr::msg::Message::raw::seqnum, olsr::msg::Message::seqnum, olsr::msg::Message::raw::size, olsr::utl::Data_< Self >::size(), olsr::msg::Message::raw::ttl, olsr::msg::Message::raw::type, and olsr::msg::Message::raw::vtime.
void olsr::msg::HNAMessage::parse (const utl::ConstData & d, const Message::header & mh) [inline, static]
The parsing method
d Message data buffer
mh Message header
References ADDRESS_SIZE, olsr::cproxy, olsr::dump_hna, olsr::hna_set, olsr::set::HNASet::insert(), olsr::set::CoherenceProxy::linkset(), olsr::set::Link::make_key(), olsr::msg::Message::header::mseqnum, olsr::net::IPv6Address::netmask_to_prefix(), olsr::msg::Message::header::originator, olsr::msg::Message::header::pseqnum, olsr::utl::Data_< Self >::raw(), olsr::msg::Message::header::receiver, olsr::msg::Message::header::sender, olsr::utl::Data_< Self >::size(), and olsr::msg::Message::header::validity.
Referenced by olsr::msg::Message::parse().
Member Data Documentation
const ::size_t olsr::msg::HNAMessage::min_length = ADDRESS_SIZE * 2 [static]
Minimum lenght of HNA message.
Reimplemented from olsr::msg::Message.
Referenced by dump().
utl::Data olsr::msg::HNAMessage::_data [private]
The message data buffer.
Referenced by dump().
The documentation for this class was generated from the following files:
msg/hna.hh
msg/hna.hxx