Qolyester daemon: olsr::set::DuplicateSet Class Reference
olsr::set::DuplicateSet Class Reference
#include <duplicate.hh>
Public Types
typedef val_dset_t dupset_t
Public Member Functions
dupset_t & dupset ()
DuplicateSet ()
void insert (const DuplicateEntry &x)
void erase (const dset_t::iterator &pos)
Private Types
typedef DuplicateSet This
typedef sch::Updatable
< DuplicateEntry > elem_t
typedef std::set< elem_t > dset_t
typedef sch::upd::SetEraser
< This, dset_t::iterator > eraser_t
typedef sch::UpdateEvent
< eraser_t > updater_t
typedef utl::Subset< dset_t,
utl::NoAction< This,
dset_t::iterator >
, utl::DefaultPredicate< This,
dset_t::iterator >, This > val_dset_t
Private Attributes
dset_t dset_
dupset_t dupset_
Friends
class sch::StatePrinter
Member Typedef Documentation
typedef DuplicateSet olsr::set::DuplicateSet::This [private]
typedef sch::Updatable<DuplicateEntry> olsr::set::DuplicateSet::elem_t [private]
typedef std::set<elem_t> olsr::set::DuplicateSet::dset_t [private]
typedef sch::upd::SetEraser<This, dset_t::iterator> olsr::set::DuplicateSet::eraser_t [private]
typedef sch::UpdateEvent<eraser_t> olsr::set::DuplicateSet::updater_t [private]
typedef utl::Subset<dset_t, utl::NoAction<This, dset_t::iterator>, utl::DefaultPredicate<This, dset_t::iterator>, This> olsr::set::DuplicateSet::val_dset_t [private]
typedef val_dset_t olsr::set::DuplicateSet::dupset_t
Constructor & Destructor Documentation
olsr::set::DuplicateSet::DuplicateSet () [inline]
Member Function Documentation
dupset_t& olsr::set::DuplicateSet::dupset () [inline]
References dupset_.
Referenced by olsr::msg::Message::forward(), and olsr::msg::Message::parse().
void olsr::set::DuplicateSet::insert (const DuplicateEntry & x) [inline]
References dset_, olsr::sch::Scheduler::erase(), olsr::set::DuplicateEntry::ifaces(), olsr::sch::Scheduler::insert(), olsr::set::DuplicateEntry::retransmitted(), olsr::scheduler, olsr::sch::TimedEvent::set_next(), and olsr::set::DuplicateEntry::time().
Referenced by olsr::msg::Message::forward().
void olsr::set::DuplicateSet::erase (const dset_t::iterator & pos) [inline]
References olsr::sch::Scheduler::destroy(), dset_, and olsr::scheduler.
Friends And Related Function Documentation
friend class sch::StatePrinter [friend]
Member Data Documentation
dset_t olsr::set::DuplicateSet::dset_ [private]
Referenced by erase(), olsr::sch::StatePrinter::handle(), and insert().
dupset_t olsr::set::DuplicateSet::dupset_ [private]
Referenced by dupset().
The documentation for this class was generated from the following files:
duplicate.hh
duplicate.hxx