Qolyester daemon: olsr::set::MIDSet Class Reference
olsr::set::MIDSet Class Reference
#include <mid.hh>
Public Types
typedef val_mset_t midset_t
Public Member Functions
midset_t & midset ()
MIDSet ()
void insert (const MIDEntry &x)
void erase (const mset_t::iterator &pos)
Private Types
typedef MIDSet This
typedef sch::Updatable< MIDEntry > elem_t
typedef std::set< elem_t > mset_t
typedef sch::upd::SetEraser
< This, mset_t::iterator > eraser_t
typedef sch::UpdateEvent
< eraser_t > updater_t
typedef utl::Subset< mset_t,
utl::NoAction< This,
mset_t::iterator >
, utl::DefaultPredicate< This,
mset_t::iterator >, This > val_mset_t
Private Attributes
mset_t mset_
midset_t midset_
Friends
class sch::StatePrinter
Member Typedef Documentation
typedef MIDSet olsr::set::MIDSet::This [private]
typedef sch::Updatable<MIDEntry> olsr::set::MIDSet::elem_t [private]
typedef std::set<elem_t> olsr::set::MIDSet::mset_t [private]
typedef sch::upd::SetEraser<This, mset_t::iterator> olsr::set::MIDSet::eraser_t [private]
typedef sch::UpdateEvent<eraser_t> olsr::set::MIDSet::updater_t [private]
typedef utl::Subset<mset_t, utl::NoAction<This, mset_t::iterator>, utl::DefaultPredicate<This, mset_t::iterator>, This> olsr::set::MIDSet::val_mset_t [private]
typedef val_mset_t olsr::set::MIDSet::midset_t
Constructor & Destructor Documentation
olsr::set::MIDSet::MIDSet () [inline]
Member Function Documentation
midset_t& olsr::set::MIDSet::midset () [inline]
References midset_.
Referenced by olsr::alg::compute_routes(), and olsr::alg::main_addr_of().
void olsr::set::MIDSet::insert (const MIDEntry & x) [inline]
References olsr::sch::Scheduler::erase(), olsr::sch::Scheduler::insert(), olsr::set::MIDEntry::main_addr(), mset_, olsr::routes_recomp, olsr::scheduler, olsr::utl::Mark::set_mark(), olsr::sch::TimedEvent::set_next(), and olsr::set::MIDEntry::time().
Referenced by olsr::msg::MIDMessage::parse().
void olsr::set::MIDSet::erase (const mset_t::iterator & pos) [inline]
References olsr::sch::Scheduler::destroy(), mset_, olsr::routes_recomp, olsr::scheduler, and olsr::utl::Mark::set_mark().
Friends And Related Function Documentation
friend class sch::StatePrinter [friend]
Member Data Documentation
mset_t olsr::set::MIDSet::mset_ [private]
Referenced by erase(), olsr::sch::StatePrinter::handle(), and insert().
midset_t olsr::set::MIDSet::midset_ [private]
Referenced by midset().
The documentation for this class was generated from the following files:
set/mid.hh
set/mid.hxx