Qolyester daemon: olsr::utl::LevelableBuf Class Reference
olsr::utl::LevelableBuf Class Reference
#include <log.hh>
Public Member Functions
virtual ~LevelableBuf ()
virtual void increase_level (unsigned i=1)=0
virtual void decrease_level (unsigned i=1)=0
virtual void reset_level ()=0
Constructor & Destructor Documentation
virtual olsr::utl::LevelableBuf::~LevelableBuf () [inline, virtual]
Member Function Documentation
virtual void olsr::utl::LevelableBuf::increase_level (unsigned i = 1) [pure virtual]
Implemented in olsr::utl::PrefixBuf< F, C, T >, olsr::utl::basic_ybuf< C, T >, and olsr::utl::basic_levelbuf< C, T >.
Referenced by olsr::utl::basic_ybuf< C, T >::increase_level(), olsr::utl::PrefixBuf< F, C, T >::increase_level(), olsr::utl::operator<<(), and olsr::utl::up().
virtual void olsr::utl::LevelableBuf::decrease_level (unsigned i = 1) [pure virtual]
Implemented in olsr::utl::PrefixBuf< F, C, T >, olsr::utl::basic_ybuf< C, T >, and olsr::utl::basic_levelbuf< C, T >.
Referenced by olsr::utl::basic_ybuf< C, T >::decrease_level(), olsr::utl::PrefixBuf< F, C, T >::decrease_level(), olsr::utl::down(), and olsr::utl::operator<<().
virtual void olsr::utl::LevelableBuf::reset_level () [pure virtual]
Implemented in olsr::utl::PrefixBuf< F, C, T >, olsr::utl::basic_ybuf< C, T >, and olsr::utl::basic_levelbuf< C, T >.
Referenced by olsr::utl::reset(), olsr::utl::basic_ybuf< C, T >::reset_level(), and olsr::utl::PrefixBuf< F, C, T >::reset_level().
The documentation for this class was generated from the following file:
log.hh