Qolyester daemon: olsr::sys::netlink::NLAddrAttrAddress Class Reference
olsr::sys::netlink::NLAddrAttrAddress Class Reference
#include <netlink.hh>
Public Member Functions
NLAddrAttrAddress (const unsigned char *b, unsigned len)
virtual ~NLAddrAttrAddress ()
virtual void accept (Visitor &v) const
const unsigned char * bytes () const
unsigned length () const
Private Attributes
unsigned char * _bytes
unsigned _len
Constructor & Destructor Documentation
olsr::sys::netlink::NLAddrAttrAddress::NLAddrAttrAddress (const unsigned char * b, unsigned len) [inline]
References _bytes.
virtual olsr::sys::netlink::NLAddrAttrAddress::~NLAddrAttrAddress () [inline, virtual]
References _bytes.
Member Function Documentation
virtual void olsr::sys::netlink::NLAddrAttrAddress::accept (Visitor & v) const [inline, virtual]
Implements olsr::sys::netlink::NLAddrAttr.
const unsigned char* olsr::sys::netlink::NLAddrAttrAddress::bytes () const [inline]
References _bytes.
Referenced by olsr::sys::netlink::RequestVisitor::visit(), and olsr::sys::netlink::InitVisitor::visit().
unsigned olsr::sys::netlink::NLAddrAttrAddress::length () const [inline]
References _len.
Referenced by olsr::sys::netlink::RequestVisitor::visit(), and olsr::sys::netlink::InitVisitor::visit().
Member Data Documentation
unsigned char* olsr::sys::netlink::NLAddrAttrAddress::_bytes [private]
Referenced by bytes(), NLAddrAttrAddress(), and ~NLAddrAttrAddress().
unsigned olsr::sys::netlink::NLAddrAttrAddress::_len [private]
Referenced by length().
The documentation for this class was generated from the following file:
netlink.hh