Qolyester daemon: olsr::utl::MSIndex< Set, Dim, Key, Comp > Class Template Reference
olsr::utl::MSIndex< Set, Dim, Key, Comp > Class Template Reference
#include <set.hh>
Public Types
typedef Key key_type
typedef Iter value_type
typedef KeyedIterator< Key,
d_iterator_ > const_iterator
typedef const_iterator iterator
Public Member Functions
MSIndex (const Set &s)
iterator begin (const Key &k) const
iterator end (const Key &k) const
iterator find (const Key &k, const Iter &x) const
void insert (const Iter &x)
void erase (const Iter &x)
void set_stamp (const_iterator pos, const TimeVal &now=TimeVal::now())
const TimeVal stamp (const_iterator pos) const
bool expired (const_iterator pos, const TimeVal &period, const TimeVal &now=TimeVal::now()) const
void add_key (const Key &k)
void remove_key (const Key &k)
Private Types
typedef MSIndex< Set, Dim, Key,
Comp > This
typedef Set::iterator Iter
typedef Set::key_compare IterComp
typedef Set::value_type Value
typedef type_traits< Value >
::const_val CElem
typedef std::multiset< Iter, Comp > set_t
typedef std::map< Key, set_t > setmap_t
typedef set_t::const_iterator c_iterator_
typedef DerefIterator
< c_iterator_ > d_iterator_
Private Attributes
setmap_t m_
const IterComp & c_
const Set & s_
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>>
class olsr::utl::MSIndex< Set, Dim, Key, Comp >
Member Typedef Documentation
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> typedef MSIndex<Set, Dim, Key, Comp> olsr::utl::MSIndex< Set, Dim, Key, Comp >::This [private]
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> typedef Set::iterator olsr::utl::MSIndex< Set, Dim, Key, Comp >::Iter [private]
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> typedef Set::key_compare olsr::utl::MSIndex< Set, Dim, Key, Comp >::IterComp [private]
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> typedef Set::value_type olsr::utl::MSIndex< Set, Dim, Key, Comp >::Value [private]
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> typedef type_traits<Value>::const_val olsr::utl::MSIndex< Set, Dim, Key, Comp >::CElem [private]
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> typedef std::multiset<Iter, Comp> olsr::utl::MSIndex< Set, Dim, Key, Comp >::set_t [private]
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> typedef std::map<Key, set_t> olsr::utl::MSIndex< Set, Dim, Key, Comp >::setmap_t [private]
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> typedef set_t::const_iterator olsr::utl::MSIndex< Set, Dim, Key, Comp >::c_iterator_ [private]
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> typedef DerefIterator<c_iterator_> olsr::utl::MSIndex< Set, Dim, Key, Comp >::d_iterator_ [private]
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> typedef Key olsr::utl::MSIndex< Set, Dim, Key, Comp >::key_type
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> typedef Iter olsr::utl::MSIndex< Set, Dim, Key, Comp >::value_type
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> typedef KeyedIterator<Key, d_iterator_> olsr::utl::MSIndex< Set, Dim, Key, Comp >::const_iterator
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> typedef const_iterator olsr::utl::MSIndex< Set, Dim, Key, Comp >::iterator
Constructor & Destructor Documentation
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> olsr::utl::MSIndex< Set, Dim, Key, Comp >::MSIndex (const Set & s) [inline]
Member Function Documentation
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> iterator olsr::utl::MSIndex< Set, Dim, Key, Comp >::begin (const Key & k) const [inline]
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> iterator olsr::utl::MSIndex< Set, Dim, Key, Comp >::end (const Key & k) const [inline]
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> iterator olsr::utl::MSIndex< Set, Dim, Key, Comp >::find (const Key & k, const Iter & x) const [inline]
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> void olsr::utl::MSIndex< Set, Dim, Key, Comp >::insert (const Iter & x) [inline]
Referenced by olsr::set::InterfaceSet::insert(), olsr::set::GateSet::insert(), and olsr::set::CoherenceProxy::insert_link().
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> void olsr::utl::MSIndex< Set, Dim, Key, Comp >::erase (const Iter & x) [inline]
Referenced by olsr::set::CoherenceProxy::erase(), olsr::set::InterfaceSet::erase(), olsr::set::GateSet::erase(), and olsr::set::CoherenceProxy::erase_from_all().
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> void olsr::utl::MSIndex< Set, Dim, Key, Comp >::set_stamp (const_iterator pos, const TimeVal & now = TimeVal::now()) [inline]
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> const TimeVal olsr::utl::MSIndex< Set, Dim, Key, Comp >::stamp (const_iterator pos) const [inline]
Referenced by olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::set_stamp().
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> bool olsr::utl::MSIndex< Set, Dim, Key, Comp >::expired (const_iterator pos, const TimeVal & period, const TimeVal & now = TimeVal::now()) const [inline]
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> void olsr::utl::MSIndex< Set, Dim, Key, Comp >::add_key (const Key & k) [inline]
Referenced by olsr::set::CoherenceProxy::add_interface(), and olsr::set::InterfaceSet::insert().
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> void olsr::utl::MSIndex< Set, Dim, Key, Comp >::remove_key (const Key & k) [inline]
Referenced by olsr::set::InterfaceSet::erase(), and olsr::set::CoherenceProxy::remove_interface().
Member Data Documentation
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> setmap_t olsr::utl::MSIndex< Set, Dim, Key, Comp >::m_ [private]
Referenced by olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::add_key(), olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::begin(), olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::end(), olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::erase(), olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::find(), olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::insert(), olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::remove_key(), and olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::set_stamp().
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> const IterComp& olsr::utl::MSIndex< Set, Dim, Key, Comp >::c_ [private]
Referenced by olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::erase().
template<class Set, unsigned Dim, class Key, class Comp = imultistampable_less<Key, typename Set::iterator>> const Set& olsr::utl::MSIndex< Set, Dim, Key, Comp >::s_ [private]
Referenced by olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::add_key().
The documentation for this class was generated from the following file:
set.hh