Qolyester daemon: olsr::set::GateSet Class Reference
olsr::set::GateSet Class Reference
#include <gate.hh>
Public Types
typedef idx_gset_t hna_gset_t
typedef gset_t::const_iterator const_iterator
typedef const_iterator iterator
Public Member Functions
hna_gset_t & hna_gset ()
GateSet ()
iterator begin () const
iterator end () const
std::pair< iterator, bool > insert (const gset_t::value_type &x)
void erase (iterator pos)
bool empty () const
Private Types
typedef GateSet This
typedef GateEntry elem_t
typedef std::set< elem_t > gset_t
typedef utl::MSIndex< gset_t,
0, address_t > idx_gset_t
Private Attributes
gset_t gset_
idx_gset_t hna_gset_
Member Typedef Documentation
typedef GateSet olsr::set::GateSet::This [private]
typedef GateEntry olsr::set::GateSet::elem_t [private]
typedef std::set<elem_t> olsr::set::GateSet::gset_t [private]
typedef utl::MSIndex<gset_t, 0, address_t> olsr::set::GateSet::idx_gset_t [private]
typedef idx_gset_t olsr::set::GateSet::hna_gset_t
typedef gset_t::const_iterator olsr::set::GateSet::const_iterator
typedef const_iterator olsr::set::GateSet::iterator
Constructor & Destructor Documentation
olsr::set::GateSet::GateSet () [inline]
Member Function Documentation
hna_gset_t& olsr::set::GateSet::hna_gset () [inline]
References hna_gset_.
Referenced by olsr::msg::HNAMessage::dump(), olsr::set::InterfaceSet::erase(), and olsr::set::InterfaceSet::insert().
iterator olsr::set::GateSet::begin () const [inline]
References gset_.
Referenced by main().
iterator olsr::set::GateSet::end () const [inline]
References gset_.
Referenced by main().
std::pair< GateSet::iterator, bool > olsr::set::GateSet::insert (const gset_t::value_type & x) [inline]
References gset_, hna_gset_, and olsr::utl::MSIndex< Set, Dim, Key, Comp >::insert().
Referenced by olsr::utl::parse_args().
void olsr::set::GateSet::erase (iterator pos) [inline]
References olsr::utl::MSIndex< Set, Dim, Key, Comp >::erase(), gset_, and hna_gset_.
bool olsr::set::GateSet::empty () const [inline]
References gset_.
Referenced by olsr::msg::HNAMessage::dump(), and main().
Member Data Documentation
gset_t olsr::set::GateSet::gset_ [private]
Referenced by begin(), empty(), end(), erase(), and insert().
idx_gset_t olsr::set::GateSet::hna_gset_ [private]
Referenced by erase(), hna_gset(), and insert().
The documentation for this class was generated from the following files:
gate.hh
gate.hxx