Qolyester daemon: olsr::set::InterfaceSet Class Reference
olsr::set::InterfaceSet Class Reference
#include <interfaces.hh>
Public Types
typedef idx_iset_t mid_iset_t
typedef iset_t::const_iterator const_iterator
typedef const_iterator iterator
Public Member Functions
mid_iset_t & mid_iset ()
InterfaceSet ()
iterator begin () const
iterator end () const
iterator find (const address_t &iaddr) const
bool empty () const
size_t size () const
unsigned min_mtu () const
const iface_t & operator[] (const address_t &iaddr) const
std::pair< iterator, bool > insert (const iset_t::value_type &x)
void erase (iterator pos)
void send_messages ()
Private Types
typedef InterfaceSet This
typedef std::set< iface_t > iset_t
typedef utl::MSIndex< iset_t,
0, address_t > idx_iset_t
Private Attributes
iset_t _iset
mid_iset_t _mid_iset
unsigned _min_mtu
Member Typedef Documentation
typedef InterfaceSet olsr::set::InterfaceSet::This [private]
typedef std::set<iface_t> olsr::set::InterfaceSet::iset_t [private]
typedef utl::MSIndex<iset_t, 0, address_t> olsr::set::InterfaceSet::idx_iset_t [private]
typedef idx_iset_t olsr::set::InterfaceSet::mid_iset_t
typedef iset_t::const_iterator olsr::set::InterfaceSet::const_iterator
typedef const_iterator olsr::set::InterfaceSet::iterator
Constructor & Destructor Documentation
olsr::set::InterfaceSet::InterfaceSet () [inline]
Member Function Documentation
mid_iset_t& olsr::set::InterfaceSet::mid_iset () [inline]
References _mid_iset.
Referenced by olsr::msg::MIDMessage::dump().
InterfaceSet::iterator olsr::set::InterfaceSet::begin () const [inline]
References _iset.
Referenced by main(), and olsr::alg::mprselection().
InterfaceSet::iterator olsr::set::InterfaceSet::end () const [inline]
References _iset.
Referenced by olsr::sys::RealInterfaceInfo::del_addr(), erase(), main(), olsr::alg::main_addr_of(), olsr::alg::mprselection(), and operator[]().
InterfaceSet::iterator olsr::set::InterfaceSet::find (const address_t & iaddr) const [inline]
References _iset, and olsr::net::RealInterface::make_key().
Referenced by olsr::sys::RealInterfaceInfo::del_addr(), olsr::alg::main_addr_of(), and operator[]().
bool olsr::set::InterfaceSet::empty () const [inline]
References _iset.
Referenced by main(), and send_messages().
size_t olsr::set::InterfaceSet::size () const [inline]
References _iset.
Referenced by main().
unsigned olsr::set::InterfaceSet::min_mtu () const [inline]
References _min_mtu.
Referenced by send_messages().
const iface_t & olsr::set::InterfaceSet::operator[] (const address_t & iaddr) const [inline]
References end(), and find().
std::pair< InterfaceSet::iterator, bool > olsr::set::InterfaceSet::insert (const iset_t::value_type & x) [inline]
References _iset, _mid_iset, _min_mtu, olsr::set::CoherenceProxy::add_interface(), olsr::utl::MSIndex< Set, Dim, Key, Comp >::add_key(), olsr::cproxy, olsr::gate_set, olsr::set::GateSet::hna_gset(), olsr::sch::Scheduler::insert(), olsr::utl::MSIndex< Set, Dim, Key, Comp >::insert(), olsr::main_addr, and olsr::scheduler.
Referenced by olsr::utl::parse_args().
void olsr::set::InterfaceSet::erase (iterator pos) [inline]
References _iset, _mid_iset, _min_mtu, olsr::cproxy, end(), olsr::utl::MSIndex< Set, Dim, Key, Comp >::erase(), olsr::gate_set, olsr::set::GateSet::hna_gset(), olsr::main_addr, olsr::set::CoherenceProxy::remove_interface(), and olsr::utl::MSIndex< Set, Dim, Key, Comp >::remove_key().
void olsr::set::InterfaceSet::send_messages () [inline]
References _iset, _min_mtu, empty(), olsr::iface_set, olsr::pkt::Packet::min_length, min_mtu(), and olsr::pending_messages.
Referenced by olsr::sch::QolyesterLoopHandler::operator()().
Member Data Documentation
iset_t olsr::set::InterfaceSet::_iset [private]
Referenced by begin(), empty(), end(), erase(), find(), insert(), send_messages(), and size().
mid_iset_t olsr::set::InterfaceSet::_mid_iset [private]
Referenced by erase(), insert(), and mid_iset().
unsigned olsr::set::InterfaceSet::_min_mtu [private]
Referenced by erase(), insert(), min_mtu(), and send_messages().
The documentation for this class was generated from the following files:
interfaces.hh
interfaces.hxx