Qolyester daemon: olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet > Class Template Reference
olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet > Class Template Reference
#include <iterator.hh>
Public Member Functions
operator Super () const
const Super & mask_super () const
Super & mask_super ()
MaskIterator ()
MaskIterator (const Super &other, Set &instance, const Key &key)
MaskIterator (const Super &other, Set &instance, ActionSet &ainstance, const Key &key)
const Elem & operator* () const
const Elem * operator-> () const
This & operator++ ()
This operator++ (int)
bool operator== (const This &rhs) const
bool operator!= (const This &rhs) const
bool is_valid () const
This & skip ()
void destroy ()
This & check ()
Private Types
typedef Set::iterator Super
typedef std::iterator_traits
< Super >::value_type Elem
typedef Set::key_type Key
typedef MaskIterator< MSAdapt
< Set >, Action, Predicate,
ActionSet > This
Private Attributes
Super _super
Set * _instance
ActionSet * _action_instance
Key _key
template<class Set, class Action, class Predicate, class ActionSet>
class olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >
Member Typedef Documentation
template<class Set, class Action, class Predicate, class ActionSet> typedef Set::iterator olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::Super [private]
template<class Set, class Action, class Predicate, class ActionSet> typedef std::iterator_traits<Super>::value_type olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::Elem [private]
template<class Set, class Action, class Predicate, class ActionSet> typedef Set::key_type olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::Key [private]
template<class Set, class Action, class Predicate, class ActionSet> typedef MaskIterator<MSAdapt<Set>, Action, Predicate, ActionSet> olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::This [private]
Constructor & Destructor Documentation
template<class Set, class Action, class Predicate, class ActionSet> olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::MaskIterator () [inline]
template<class Set, class Action, class Predicate, class ActionSet> olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::MaskIterator (const Super & other, Set & instance, const Key & key) [inline]
template<class Set, class Action, class Predicate, class ActionSet> olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::MaskIterator (const Super & other, Set & instance, ActionSet & ainstance, const Key & key) [inline]
Member Function Documentation
template<class Set, class Action, class Predicate, class ActionSet> olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::operator Super () const [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super.
template<class Set, class Action, class Predicate, class ActionSet> const Super& olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::mask_super () const [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super.
template<class Set, class Action, class Predicate, class ActionSet> Super& olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::mask_super () [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super.
template<class Set, class Action, class Predicate, class ActionSet> const Elem& olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::operator* () const [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super.
template<class Set, class Action, class Predicate, class ActionSet> const Elem* olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::operator-> () const [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super.
template<class Set, class Action, class Predicate, class ActionSet> This& olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::operator++ () [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super, and olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::skip().
template<class Set, class Action, class Predicate, class ActionSet> This olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::operator++ (int) [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator++().
template<class Set, class Action, class Predicate, class ActionSet> bool olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::operator== (const This & rhs) const [inline]
References _super, and olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super.
template<class Set, class Action, class Predicate, class ActionSet> bool olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::operator!= (const This & rhs) const [inline]
References _super, and olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super.
template<class Set, class Action, class Predicate, class ActionSet> bool olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::is_valid () const [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_action_instance, olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_instance, olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super, and olsr::utl::Set< Elem, Iset, Iter, CIter >::end().
template<class Set, class Action, class Predicate, class ActionSet> This& olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::skip () [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_action_instance, _super, olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super, and olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::is_valid().
template<class Set, class Action, class Predicate, class ActionSet> void olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::destroy () [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_action_instance, olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_instance, olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super, and olsr::utl::Set< Elem, Iset, Iter, CIter >::end().
template<class Set, class Action, class Predicate, class ActionSet> This& olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::check () [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_instance, and olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::is_valid().
Member Data Documentation
template<class Set, class Action, class Predicate, class ActionSet> Super olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::_super [private]
Referenced by operator!=(), operator==(), and skip().
template<class Set, class Action, class Predicate, class ActionSet> Set* olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::_instance [private]
template<class Set, class Action, class Predicate, class ActionSet> ActionSet* olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::_action_instance [private]
template<class Set, class Action, class Predicate, class ActionSet> Key olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::_key [private]
The documentation for this class was generated from the following file:
iterator.hh