Qolyester daemon: olsr::utl::MultiStampable< Dim, Key, Compare > Class Template Reference
olsr::utl::MultiStampable< Dim, Key, Compare > Class Template Reference
#include <stampable.hh>
Public Member Functions
void set_stamp (unsigned d, const Key &k, const TimeVal &now=TimeVal::now())
void remove_stamp (unsigned d, const Key &k)
const TimeVal stamp (unsigned d, const Key &k) const
bool expired (unsigned d, const Key &k, const TimeVal &period, const TimeVal &now=TimeVal::now()) const
bool less (unsigned d, const Key &k, const This &rhs) const
Protected Member Functions
MultiStampable ()
Private Types
typedef MultiStampable< Dim,
Key, Compare > This
typedef std::map< Key, TimeVal > stampset_t
Private Attributes
stampset_t _stampset [Dim]
template<unsigned Dim, class Key, class Compare = pless<Key>>
class olsr::utl::MultiStampable< Dim, Key, Compare >
Member Typedef Documentation
template<unsigned Dim, class Key, class Compare = pless<Key>> typedef MultiStampable<Dim, Key, Compare> olsr::utl::MultiStampable< Dim, Key, Compare >::This [private]
Reimplemented in olsr::net::RealInterface, olsr::set::GateEntry, olsr::set::Link, and olsr::set::Neighbor.
template<unsigned Dim, class Key, class Compare = pless<Key>> typedef std::map<Key, TimeVal> olsr::utl::MultiStampable< Dim, Key, Compare >::stampset_t [private]
Constructor & Destructor Documentation
template<unsigned Dim, class Key, class Compare> olsr::utl::MultiStampable< Dim, Key, Compare >::MultiStampable () [inline, protected]
Member Function Documentation
template<unsigned Dim, class Key, class Compare> void olsr::utl::MultiStampable< Dim, Key, Compare >::set_stamp (unsigned d, const Key & k, const TimeVal & now = TimeVal::now()) [inline]
References olsr::utl::MultiStampable< Dim, Key, Compare >::_stampset.
Referenced by olsr::utl::MultiStampable< 1, Key, Compare >::set_stamp().
template<unsigned Dim, class Key, class Compare> void olsr::utl::MultiStampable< Dim, Key, Compare >::remove_stamp (unsigned d, const Key & k) [inline]
References olsr::utl::MultiStampable< Dim, Key, Compare >::_stampset.
Referenced by olsr::utl::MultiStampable< 1, Key, Compare >::remove_stamp().
template<unsigned Dim, class Key, class Compare> const TimeVal olsr::utl::MultiStampable< Dim, Key, Compare >::stamp (unsigned d, const Key & k) const [inline]
References olsr::utl::MultiStampable< Dim, Key, Compare >::_stampset.
Referenced by olsr::utl::MultiStampable< 1, Key, Compare >::expired(), olsr::utl::MultiStampable< Dim, Key, Compare >::expired(), olsr::utl::MultiStampable< 1, Key, Compare >::less(), olsr::utl::MultiStampable< Dim, Key, Compare >::less(), and olsr::utl::MultiStampable< 1, Key, Compare >::stamp().
template<unsigned Dim, class Key, class Compare> bool olsr::utl::MultiStampable< Dim, Key, Compare >::expired (unsigned d, const Key & k, const TimeVal & period, const TimeVal & now = TimeVal::now()) const [inline]
References olsr::utl::MultiStampable< Dim, Key, Compare >::stamp().
Referenced by olsr::utl::MultiStampable< 1, Key, Compare >::expired().
template<unsigned Dim, class Key, class Compare> bool olsr::utl::MultiStampable< Dim, Key, Compare >::less (unsigned d, const Key & k, const This & rhs) const [inline]
References olsr::utl::MultiStampable< Dim, Key, Compare >::stamp().
Referenced by olsr::utl::MultiStampable< 1, Key, Compare >::less(), olsr::utl::multistampable_less< 1, Key, Compare >::operator()(), and olsr::utl::multistampable_less< Dim, Key, Compare >::operator()().
Member Data Documentation
template<unsigned Dim, class Key, class Compare = pless<Key>> stampset_t olsr::utl::MultiStampable< Dim, Key, Compare >::_stampset[Dim] [private]
Referenced by olsr::utl::MultiStampable< 1, Key, Compare >::remove_stamp(), olsr::utl::MultiStampable< Dim, Key, Compare >::remove_stamp(), olsr::utl::MultiStampable< 1, Key, Compare >::set_stamp(), olsr::utl::MultiStampable< Dim, Key, Compare >::set_stamp(), olsr::utl::MultiStampable< 1, Key, Compare >::stamp(), and olsr::utl::MultiStampable< Dim, Key, Compare >::stamp().
The documentation for this class was generated from the following files:
stampable.hh
stampable.hxx