Qolyester daemon: olsr::net::LocalRoute Class Reference
olsr::net::LocalRoute Class Reference
Local route class.
#include <route.hh>
Public Member Functions
LocalRoute (const address_t &d, unsigned p, const ifaceinfo_t &i)
LocalRoute (const This &other)
const address_t & dest_addr () const
unsigned prefix () const
const ifaceinfo_t & interface_info () const
bool operator== (const This &rhs) const
Static Public Member Functions
static const This & make_key (const address_t &d, unsigned p)
Private Types
typedef LocalRoute This
Private Member Functions
LocalRoute ()
Private Attributes
const address_t _d_addr
Destination address.
const unsigned _prefix
Prefix length.
const ifaceinfo_t _info
Output interface information.
Static Private Attributes
static This _dummy_for_find
Static instance for key building.
Detailed Description
Local route class.
A local route is simply a destination address, a prefix length and an output interface.
Member Typedef Documentation
typedef LocalRoute olsr::net::LocalRoute::This [private]
Constructor & Destructor Documentation
olsr::net::LocalRoute::LocalRoute () [inline, explicit, private]
Private constructor
This is provided only for _dummy_for_find.
olsr::net::LocalRoute::LocalRoute (const address_t & d, unsigned p, const ifaceinfo_t & i) [inline]
Constructor
d Destination address
p Prefix length
i Output interface
References _info, and olsr::sys::RealInterfaceInfo::index().
olsr::net::LocalRoute::LocalRoute (const This & other) [inline]
References _info, and olsr::sys::RealInterfaceInfo::index().
Member Function Documentation
const address_t& olsr::net::LocalRoute::dest_addr () const [inline]
Destination address accessor
Returns:
Destination address
References _d_addr.
Referenced by olsr::sys::RoutingActions::add_local_route(), olsr::net::hash_LocalRoute::operator()(), and olsr::sys::RoutingActions::remove_local_route().
unsigned olsr::net::LocalRoute::prefix () const [inline]
Prefix length accessor
Returns:
Prefix length
References _prefix.
Referenced by olsr::sys::RoutingActions::add_local_route(), and olsr::sys::RoutingActions::remove_local_route().
const ifaceinfo_t& olsr::net::LocalRoute::interface_info () const [inline]
Interface accessor
Returns:
Output interface
References _info.
Referenced by olsr::sys::RoutingActions::add_local_route(), and olsr::sys::RoutingActions::remove_local_route().
bool olsr::net::LocalRoute::operator== (const This & rhs) const [inline]
Equality comparison operator
rhs RHS operand
Returns:
true if routes are equal
References _d_addr, _info, _prefix, and olsr::sys::RealInterfaceInfo::index().
const LocalRoute & olsr::net::LocalRoute::make_key (const address_t & d, unsigned p) [inline, static]
Key builder
d Destionation address
p Prefix length
Returns:
Modified instance of _dummy_for_find
References _d_addr, _dummy_for_find, and _prefix.
Referenced by olsr::operator*(), and olsr::operator-().
Member Data Documentation
const address_t olsr::net::LocalRoute::_d_addr [private]
Destination address.
Referenced by dest_addr(), make_key(), and operator==().
const unsigned olsr::net::LocalRoute::_prefix [private]
Prefix length.
Referenced by make_key(), operator==(), and prefix().
const ifaceinfo_t olsr::net::LocalRoute::_info [private]
Output interface information.
Referenced by interface_info(), LocalRoute(), and operator==().
This olsr::net::LocalRoute::_dummy_for_find [static, private]
Static instance for key building.
Referenced by make_key().
The documentation for this class was generated from the following files:
route.hh
route.hxx