Qolyester daemon: olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet > Class Template Reference
olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet > Class Template Reference
#include <iterator.hh>
Public Member Functions
operator Super () const
const Super & mask_super () const
Super & mask_super ()
MaskIterator ()
MaskIterator (const Super &other, Set &instance)
MaskIterator (const Super &other, Set &instance, ActionSet &ainstance)
const Elem & operator* () const
const Elem * operator-> () const
This & operator++ ()
This operator++ (int)
bool operator== (const This &rhs) const
bool operator!= (const This &rhs) const
bool is_valid () const
This & skip ()
void act ()
This & check ()
Private Types
typedef Set::iterator Super
typedef std::iterator_traits
< Super >::value_type Elem
typedef MaskIterator< Set,
Action, Predicate, ActionSet > This
Private Attributes
Super _super
Set * _instance
ActionSet * _action_instance
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set>
class olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >
Member Typedef Documentation
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> typedef Set::iterator olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::Super [private]
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> typedef std::iterator_traits<Super>::value_type olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::Elem [private]
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> typedef MaskIterator<Set, Action, Predicate, ActionSet> olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::This [private]
Constructor & Destructor Documentation
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::MaskIterator () [inline]
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::MaskIterator (const Super & other, Set & instance) [inline]
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::MaskIterator (const Super & other, Set & instance, ActionSet & ainstance) [inline]
Member Function Documentation
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator Super () const [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super.
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> const Super& olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::mask_super () const [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super.
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> Super& olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::mask_super () [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super.
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> const Elem& olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator* () const [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super.
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> const Elem* olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator-> () const [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super.
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> This& olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator++ () [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super, and olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::skip().
Referenced by olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::operator++(), and olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator++().
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> This olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator++ (int) [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator++().
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> bool olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator== (const This & rhs) const [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super.
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> bool olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator!= (const This & rhs) const [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super.
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> bool olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::is_valid () const [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_action_instance, olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_instance, olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super, and olsr::utl::Set< Elem, Iset, Iter, CIter >::end().
Referenced by olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::check(), olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::check(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::skip(), and olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::skip().
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> This& olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::skip () [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_action_instance, olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super, and olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::is_valid().
Referenced by olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::operator++(), and olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator++().
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> void olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::act () [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_action_instance, olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_instance, olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super, and olsr::utl::Set< Elem, Iset, Iter, CIter >::end().
Referenced by olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::check().
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> This& olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::check () [inline]
References olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_instance, olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::act(), and olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::is_valid().
Member Data Documentation
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> Super olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_super [private]
Referenced by olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::act(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::destroy(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::is_valid(), olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::is_valid(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::mask_super(), olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::mask_super(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::operator Super(), olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator Super(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::operator!=(), olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator!=(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::operator*(), olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator*(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::operator++(), olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator++(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::operator->(), olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator->(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::operator==(), olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::operator==(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::skip(), and olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::skip().
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> Set* olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_instance [private]
Referenced by olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::act(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::check(), olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::check(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::destroy(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::is_valid(), and olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::is_valid().
template<class Set, class Action = NoAction<Set>, class Predicate = DefaultPredicate<Set>, class ActionSet = Set> ActionSet* olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::_action_instance [private]
Referenced by olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::act(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::destroy(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::is_valid(), olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::is_valid(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::skip(), and olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::skip().
The documentation for this class was generated from the following file:
iterator.hh