Qolyester daemon: olsr::utl::KeyedIterator< Key, Iter > Class Template Reference
olsr::utl::KeyedIterator< Key, Iter > Class Template Reference
#include <iterator.hh>
Public Member Functions
KeyedIterator (const Super &other, const Key &k)
KeyedIterator (const This &other)
const Key & key () const
Private Types
typedef KeyedIterator< Key, Iter > This
typedef Iter Super
Private Attributes
Key _key
template<class Key, class Iter>
class olsr::utl::KeyedIterator< Key, Iter >
Member Typedef Documentation
template<class Key, class Iter> typedef KeyedIterator<Key, Iter> olsr::utl::KeyedIterator< Key, Iter >::This [private]
template<class Key, class Iter> typedef Iter olsr::utl::KeyedIterator< Key, Iter >::Super [private]
Constructor & Destructor Documentation
template<class Key, class Iter> olsr::utl::KeyedIterator< Key, Iter >::KeyedIterator (const Super & other, const Key & k) [inline]
template<class Key, class Iter> olsr::utl::KeyedIterator< Key, Iter >::KeyedIterator (const This & other) [inline]
Member Function Documentation
template<class Key, class Iter> const Key& olsr::utl::KeyedIterator< Key, Iter >::key () const [inline]
References olsr::utl::KeyedIterator< Key, Iter >::_key.
Referenced by olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::expired(), olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::set_stamp(), and olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::stamp().
Member Data Documentation
template<class Key, class Iter> Key olsr::utl::KeyedIterator< Key, Iter >::_key [private]
Referenced by olsr::utl::KeyedIterator< Key, Iter >::key().
The documentation for this class was generated from the following file:
iterator.hh