Qolyester daemon: olsr::sch::MessageSender< msg::TCMessage > Class Template Reference
olsr::sch::MessageSender< msg::TCMessage > Class Template Reference
#include <events.hh>
Public Member Functions
MessageSender ()
virtual void handle ()
Private Types
typedef MessageSender
< msg::TCMessage > This
typedef JitteredEvent Super
template<>
class olsr::sch::MessageSender< msg::TCMessage >
Member Typedef Documentation
typedef MessageSender<msg::TCMessage> olsr::sch::MessageSender< msg::TCMessage >::This [private]
Reimplemented from olsr::sch::JitteredEvent.
typedef JitteredEvent olsr::sch::MessageSender< msg::TCMessage >::Super [private]
Reimplemented from olsr::sch::JitteredEvent.
Constructor & Destructor Documentation
olsr::sch::MessageSender< msg::TCMessage >::MessageSender () [inline]
Member Function Documentation
void olsr::sch::MessageSender< msg::TCMessage >::handle () [inline, virtual]
Virtual handling method.
Reimplemented from olsr::sch::PeriodicEvent_< I >.
References olsr::cproxy, olsr::sch::PeriodicEvent_< I >::handle(), olsr::set::CoherenceProxy::is_advset_empty(), olsr::set::CoherenceProxy::is_hold_expired(), and olsr::pending_messages.
The documentation for this class was generated from the following files:
events.hh
events.hxx