Qolyester daemon: olsr::msg::MIDMessage Class Reference
olsr::msg::MIDMessage Class Reference
MID message class.
#include <mid.hh>
Public Member Functions
MIDMessage ()
MIDMessage (const utl::Data &d, const address_t &)
virtual ~MIDMessage ()
virtual bool dump (utl::Data &, const address_t &) const
Static Public Member Functions
static void parse (const utl::ConstData &, const Message::header &)
Static Public Attributes
static const ::size_t min_length = ADDRESS_SIZE
Minimum length of a MID message.
Private Types
typedef MIDMessage This
typedef Message Super
Private Attributes
utl::Data _data
The message data buffer.
Detailed Description
MID message class.
Member Typedef Documentation
typedef MIDMessage olsr::msg::MIDMessage::This [private]
typedef Message olsr::msg::MIDMessage::Super [private]
Constructor & Destructor Documentation
olsr::msg::MIDMessage::MIDMessage () [inline]
The default constructor
olsr::msg::MIDMessage::MIDMessage (const utl::Data & d, const address_t &) [inline]
The constructor
d Message data buffer
virtual olsr::msg::MIDMessage::~MIDMessage () [inline, virtual]
The destructor
Member Function Documentation
bool olsr::msg::MIDMessage::dump (utl::Data & d, const address_t & interface) const [inline, virtual]
The dumping method
d Destination data buffer
interface Source interface address of the packet
Returns:
true if the message is to be resent
Implements olsr::msg::Message.
References _data, olsr::msg::Message::raw::addr, ADDRESS_SIZE, olsr::utl::Data_< Self >::dump(), olsr::net::IPv6Address::dump(), olsr::dump_mid, olsr::utl::Data_< Self >::empty(), olsr::msg::Message::raw::hopcount, olsr::iface_set, olsr::utl::TimeVal::in(), olsr::main_addr, olsr::set::InterfaceSet::mid_iset(), MID_MESSAGE, min_length, olsr::msg::Message::min_length, olsr::utl::TimeVal::now(), olsr::utl::Data::raw(), olsr::msg::Message::raw::seqnum, olsr::msg::Message::seqnum, olsr::msg::Message::raw::size, olsr::utl::Data_< Self >::size(), olsr::msg::Message::raw::ttl, olsr::msg::Message::raw::type, and olsr::msg::Message::raw::vtime.
void olsr::msg::MIDMessage::parse (const utl::ConstData & d, const Message::header & mh) [inline, static]
The parsing routine
d Message data buffer
mh Message header
References ADDRESS_SIZE, olsr::cproxy, olsr::dump_mid, olsr::set::MIDSet::insert(), olsr::set::CoherenceProxy::linkset(), olsr::set::Link::make_key(), olsr::mid_set, olsr::msg::Message::header::mseqnum, olsr::msg::Message::header::originator, olsr::msg::Message::header::pseqnum, olsr::utl::Data_< Self >::raw(), olsr::msg::Message::header::receiver, olsr::msg::Message::header::sender, olsr::utl::Data_< Self >::size(), and olsr::msg::Message::header::validity.
Referenced by olsr::msg::Message::parse().
Member Data Documentation
const ::size_t olsr::msg::MIDMessage::min_length = ADDRESS_SIZE [static]
Minimum length of a MID message.
Reimplemented from olsr::msg::Message.
Referenced by dump().
utl::Data olsr::msg::MIDMessage::_data [private]
The message data buffer.
Referenced by dump().
The documentation for this class was generated from the following files:
msg/mid.hh
msg/mid.hxx