Qolyester daemon: olsr::gra::hash_AdjInfo Class Reference
olsr::gra::hash_AdjInfo Class Reference
Hashing functor for AdjInfo.
#include <graph.hh>
Public Member Functions
::size_t operator() (const AdjInfo &a) const
::size_t operator() (const AdjInfo *a) const
Detailed Description
Hashing functor for AdjInfo.
Member Function Documentation
::size_t olsr::gra::hash_AdjInfo::operator() (const AdjInfo & a) const [inline]
References olsr::gra::AdjInfo::endpoint1(), and olsr::gra::AdjInfo::endpoint2().
::size_t olsr::gra::hash_AdjInfo::operator() (const AdjInfo * a) const [inline]
References olsr::gra::AdjInfo::endpoint1(), and olsr::gra::AdjInfo::endpoint2().
The documentation for this class was generated from the following file:
graph.hh