Qolyester daemon: olsr::utl::DeconstIterator< Iter > Class Template Reference
olsr::utl::DeconstIterator< Iter > Class Template Reference
#include <iterator.hh>
Public Member Functions
DeconstIterator ()
DeconstIterator (const This &other)
MRef operator* () const
MPtr operator-> () const
This & operator++ ()
This operator++ (int)
Static Public Member Functions
static This build (const Super &other)
static std::pair< This, bool > build (const std::pair< Super, bool > &p)
Private Types
typedef DeconstIterator< Iter > This
typedef Iter Super
typedef std::iterator_traits
< Iter >::value_type Elem
typedef type_traits< Elem >
::mutable_ref MRef
typedef type_traits< Elem >
::mutable_ptr MPtr
template<class Iter>
class olsr::utl::DeconstIterator< Iter >
Member Typedef Documentation
template<class Iter> typedef DeconstIterator<Iter> olsr::utl::DeconstIterator< Iter >::This [private]
template<class Iter> typedef Iter olsr::utl::DeconstIterator< Iter >::Super [private]
template<class Iter> typedef std::iterator_traits<Iter>::value_type olsr::utl::DeconstIterator< Iter >::Elem [private]
template<class Iter> typedef type_traits<Elem>::mutable_ref olsr::utl::DeconstIterator< Iter >::MRef [private]
template<class Iter> typedef type_traits<Elem>::mutable_ptr olsr::utl::DeconstIterator< Iter >::MPtr [private]
Constructor & Destructor Documentation
template<class Iter> olsr::utl::DeconstIterator< Iter >::DeconstIterator () [inline]
template<class Iter> olsr::utl::DeconstIterator< Iter >::DeconstIterator (const This & other) [inline]
Member Function Documentation
template<class Iter> MRef olsr::utl::DeconstIterator< Iter >::operator* () const [inline]
template<class Iter> MPtr olsr::utl::DeconstIterator< Iter >::operator-> () const [inline]
template<class Iter> This& olsr::utl::DeconstIterator< Iter >::operator++ () [inline]
template<class Iter> This olsr::utl::DeconstIterator< Iter >::operator++ (int) [inline]
References olsr::utl::DeconstIterator< Iter >::build().
template<class Iter> static This olsr::utl::DeconstIterator< Iter >::build (const Super & other) [inline, static]
Referenced by olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::begin(), olsr::utl::Subset< MultiAdapt< Set >, Action, Predicate, ActionSet >::begin(), olsr::utl::Subset< utl::MultiAdapt< utl::Index< std::multiset, std::set< ulink_t >, ilinkless > >, olsr::utl::NoAction< olsr::set::Neighbor, lset_t::iterator >, olsr::set::Neighbor::lset_valid, olsr::set::Neighbor >::begin(), olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::end(), olsr::utl::Subset< MultiAdapt< Set >, Action, Predicate, ActionSet >::end(), olsr::utl::Subset< utl::MultiAdapt< utl::Index< std::multiset, std::set< ulink_t >, ilinkless > >, olsr::utl::NoAction< olsr::set::Neighbor, lset_t::iterator >, olsr::set::Neighbor::lset_valid, olsr::set::Neighbor >::end(), olsr::utl::Subset< MultiAdapt< Set >, Action, Predicate, ActionSet >::equal_range(), olsr::utl::Subset< utl::MultiAdapt< utl::Index< std::multiset, std::set< ulink_t >, ilinkless > >, olsr::utl::NoAction< olsr::set::Neighbor, lset_t::iterator >, olsr::set::Neighbor::lset_valid, olsr::set::Neighbor >::find(), and olsr::utl::DeconstIterator< Iter >::operator++().
template<class Iter> static std::pair<This, bool> olsr::utl::DeconstIterator< Iter >::build (const std::pair< Super, bool > & p) [inline, static]
The documentation for this class was generated from the following file:
iterator.hh