Qolyester daemon: olsr::set::upd::LinkUpdater Class Reference
olsr::set::upd::LinkUpdater Class Reference
#include <neighbors.hh>
Public Member Functions
LinkUpdater (Set &s, const Iter &i)
void operator() ()
Static Public Member Functions
static timeval_t min_time (const Link &l)
Private Types
typedef LinkUpdater This
typedef CoherenceProxy Set
typedef sch::Updatable< Link > elem_t
typedef std::set< elem_t >
::iterator Iter
typedef sch::UpdateEvent< This > updater_t
Private Attributes
Set & set_
Iter iter_
Member Typedef Documentation
typedef LinkUpdater olsr::set::upd::LinkUpdater::This [private]
typedef CoherenceProxy olsr::set::upd::LinkUpdater::Set [private]
typedef sch::Updatable<Link> olsr::set::upd::LinkUpdater::elem_t [private]
typedef std::set<elem_t>::iterator olsr::set::upd::LinkUpdater::Iter [private]
typedef sch::UpdateEvent<This> olsr::set::upd::LinkUpdater::updater_t [private]
Constructor & Destructor Documentation
olsr::set::upd::LinkUpdater::LinkUpdater (Set & s, const Iter & i) [inline]
Member Function Documentation
void olsr::set::upd::LinkUpdater::operator() () [inline]
References olsr::debug, olsr::utl::down(), olsr::set::CoherenceProxy::erase(), olsr::sch::Scheduler::erase(), olsr::cst::hello_grace, olsr::sch::Scheduler::insert(), iter_, min_time(), olsr::scheduler, set_, olsr::sch::TimedEvent::set_next(), olsr::utl::up(), and olsr::set::CoherenceProxy::update_state().
static timeval_t olsr::set::upd::LinkUpdater::min_time (const Link & l) [inline, static]
References olsr::set::Link::asymtime(), olsr::utl::TimeVal::is_past(), olsr::set::Link::symtime(), and olsr::set::Link::time().
Referenced by operator()().
Member Data Documentation
Set& olsr::set::upd::LinkUpdater::set_ [private]
Referenced by operator()().
Iter olsr::set::upd::LinkUpdater::iter_ [private]
Referenced by operator()().
The documentation for this class was generated from the following files:
neighbors.hh
neighbors.hxx