Qolyester daemon: olsr::sys::internal::InterfaceAddress Class Reference
olsr::sys::internal::InterfaceAddress Class Reference
#include <interfacedesc.hh>
Public Member Functions
InterfaceAddress (unsigned p, unsigned char s, const address_t &a, const address_t &b)
unsigned prefix () const
unsigned char scope () const
const address_t & address () const
const address_t & broadcast () const
bool operator< (const This &rhs) const
Static Public Member Functions
static This make_key (const address_t &a)
Private Types
typedef InterfaceAddress This
Private Member Functions
InterfaceAddress ()
Private Attributes
unsigned _prefix
unsigned char _scope
const address_t _address
const address_t _broadcast
Static Private Attributes
static This _dummy_for_find
Member Typedef Documentation
typedef InterfaceAddress olsr::sys::internal::InterfaceAddress::This [private]
Constructor & Destructor Documentation
olsr::sys::internal::InterfaceAddress::InterfaceAddress () [private]
olsr::sys::internal::InterfaceAddress::InterfaceAddress (unsigned p, unsigned char s, const address_t & a, const address_t & b)
Member Function Documentation
unsigned olsr::sys::internal::InterfaceAddress::prefix () const [inline]
References _prefix.
Referenced by olsr::sys::internal::RoutingSocket::add_addr(), and olsr::sys::internal::RoutingSocket::del_addr().
unsigned char olsr::sys::internal::InterfaceAddress::scope () const [inline]
References _scope.
Referenced by olsr::sys::internal::RoutingSocket::add_addr(), and olsr::sys::internal::RoutingSocket::del_addr().
const address_t& olsr::sys::internal::InterfaceAddress::address () const [inline]
References _address.
Referenced by olsr::sys::internal::RoutingSocket::add_addr(), and olsr::sys::internal::RoutingSocket::del_addr().
const address_t& olsr::sys::internal::InterfaceAddress::broadcast () const [inline]
References _broadcast.
Referenced by olsr::sys::internal::RoutingSocket::add_addr(), and olsr::sys::internal::RoutingSocket::del_addr().
bool olsr::sys::internal::InterfaceAddress::operator< (const This & rhs) const
References _address.
InterfaceAddress olsr::sys::internal::InterfaceAddress::make_key (const address_t & a) [static]
References _address, and _dummy_for_find.
Member Data Documentation
unsigned olsr::sys::internal::InterfaceAddress::_prefix [private]
Referenced by prefix().
unsigned char olsr::sys::internal::InterfaceAddress::_scope [private]
Referenced by scope().
const address_t olsr::sys::internal::InterfaceAddress::_address [private]
Referenced by address(), make_key(), and operator<().
const address_t olsr::sys::internal::InterfaceAddress::_broadcast [private]
Referenced by broadcast().
This olsr::sys::internal::InterfaceAddress::_dummy_for_find [static, private]
Referenced by make_key().
The documentation for this class was generated from the following files:
linux/interfacedesc.hh
linux/interfacedesc.hxx