Qolyester daemon: olsr::sch::PacketSender Class Reference
olsr::sch::PacketSender Class Reference
#include <events.hh>
Public Member Functions
PacketSender (iface_t *i, const pkt::Packet &p)
virtual void handle ()
void push_packet (const pkt::Packet &p)
Private Types
typedef PacketSender This
typedef IOEvent Super
typedef std::queue< pkt::Packet > pqueue_t
Private Attributes
iface_t * iface_
pqueue_t packets_
Member Typedef Documentation
typedef PacketSender olsr::sch::PacketSender::This [private]
Reimplemented from olsr::sch::PollEvent_< P >.
typedef IOEvent olsr::sch::PacketSender::Super [private]
Reimplemented from olsr::sch::PollEvent_< P >.
typedef std::queue<pkt::Packet> olsr::sch::PacketSender::pqueue_t [private]
Constructor & Destructor Documentation
olsr::sch::PacketSender::PacketSender (iface_t * i, const pkt::Packet & p) [inline]
References olsr::net::RealInterface::insert_event(), and packets_.
Member Function Documentation
void olsr::sch::PacketSender::handle () [inline, virtual]
Virtual handling method.
Implements olsr::sch::Event.
References olsr::debug, olsr::sch::Scheduler::destroy(), olsr::utl::down(), olsr::net::RealInterface::erase_event(), iface_, olsr::sch::Scheduler::insert(), olsr::sch::PollEvent_< P >::p(), packets_, olsr::scheduler, olsr::net::RealInterface::send(), olsr::utl::up(), and olsr::warning.
void olsr::sch::PacketSender::push_packet (const pkt::Packet & p) [inline]
References olsr::debug, olsr::utl::down(), iface_, olsr::notice, packets_, olsr::net::RealInterface::queue_size(), and olsr::utl::up().
Referenced by olsr::net::RealInterface::shipout().
Member Data Documentation
iface_t* olsr::sch::PacketSender::iface_ [private]
Referenced by handle(), and push_packet().
pqueue_t olsr::sch::PacketSender::packets_ [private]
Referenced by handle(), PacketSender(), and push_packet().
The documentation for this class was generated from the following files:
events.hh
events.hxx