Qolyester daemon: olsr::sys::netlink::NLNewAddr Class Reference
olsr::sys::netlink::NLNewAddr Class Reference
#include <netlink.hh>
Public Types
typedef std::list< NLAddrAttr * > attrs_t
Public Member Functions
NLNewAddr (unsigned char f, unsigned char p, unsigned char fl, unsigned char s, int i)
virtual ~NLNewAddr ()
virtual void accept (Visitor &v) const
unsigned char family () const
unsigned char prefixlen () const
unsigned char flags () const
unsigned char scope () const
unsigned index () const
const attrs_t & attrs () const
void add_attr (NLAddrAttr *a)
Private Attributes
unsigned char _family
unsigned char _prefixlen
unsigned char _flags
unsigned char _scope
unsigned _index
attrs_t _attrs
Member Typedef Documentation
typedef std::list<NLAddrAttr*> olsr::sys::netlink::NLNewAddr::attrs_t
Constructor & Destructor Documentation
olsr::sys::netlink::NLNewAddr::NLNewAddr (unsigned char f, unsigned char p, unsigned char fl, unsigned char s, int i) [inline]
virtual olsr::sys::netlink::NLNewAddr::~NLNewAddr () [inline, virtual]
References _attrs.
Member Function Documentation
virtual void olsr::sys::netlink::NLNewAddr::accept (Visitor & v) const [inline, virtual]
Implements olsr::sys::netlink::NLMessage.
unsigned char olsr::sys::netlink::NLNewAddr::family () const [inline]
References _family.
Referenced by olsr::sys::netlink::RequestVisitor::visit(), and olsr::sys::netlink::InitVisitor::visit().
unsigned char olsr::sys::netlink::NLNewAddr::prefixlen () const [inline]
References _prefixlen.
Referenced by olsr::sys::netlink::RequestVisitor::visit(), and olsr::sys::netlink::InitVisitor::visit().
unsigned char olsr::sys::netlink::NLNewAddr::flags () const [inline]
References _flags.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
unsigned char olsr::sys::netlink::NLNewAddr::scope () const [inline]
References _scope.
Referenced by olsr::sys::netlink::RequestVisitor::visit(), and olsr::sys::netlink::InitVisitor::visit().
unsigned olsr::sys::netlink::NLNewAddr::index () const [inline]
References _index.
Referenced by olsr::sys::netlink::RequestVisitor::visit(), and olsr::sys::netlink::InitVisitor::visit().
const attrs_t& olsr::sys::netlink::NLNewAddr::attrs () const [inline]
References _attrs.
Referenced by olsr::sys::netlink::RequestVisitor::visit(), and olsr::sys::netlink::InitVisitor::visit().
void olsr::sys::netlink::NLNewAddr::add_attr (NLAddrAttr * a) [inline]
References _attrs.
Referenced by olsr::sys::netlink::NLSocket::receive().
Member Data Documentation
unsigned char olsr::sys::netlink::NLNewAddr::_family [private]
Referenced by family().
unsigned char olsr::sys::netlink::NLNewAddr::_prefixlen [private]
Referenced by prefixlen().
unsigned char olsr::sys::netlink::NLNewAddr::_flags [private]
Referenced by flags().
unsigned char olsr::sys::netlink::NLNewAddr::_scope [private]
Referenced by scope().
unsigned olsr::sys::netlink::NLNewAddr::_index [private]
Referenced by index().
attrs_t olsr::sys::netlink::NLNewAddr::_attrs [private]
Referenced by add_attr(), attrs(), and ~NLNewAddr().
The documentation for this class was generated from the following file:
netlink.hh