Qolyester daemon: olsr::pkt::Packet Class Reference
olsr::pkt::Packet Class Reference
#include <packet.hh>
Public Member Functions
Packet (const ::size_t mtu, const address_t &addr)
Packet (const address_t &addr, const utl::Data &d)
::size_t size () const
const utl::Data & data () const
const address_t & sender () const
bool add_message (const msg::Message &m)
void close (const address_t &i)
Static Public Member Functions
static void parse (utl::Data, const address_t &sender, const address_t &receiver)
Static Public Attributes
static const ::size_t min_length = sizeof (raw)
Static Protected Attributes
static std::map< address_t,
utl::Seqnum< u_int16_t > > seqnum_map = std::map<address_t, utl::Seqnum<u_int16_t> >()
Private Attributes
::size_t _size
address_t _sender
utl::Data _data
raw * _raw
Classes
struct raw
Constructor & Destructor Documentation
olsr::pkt::Packet::Packet (const ::size_t mtu, const address_t & addr) [inline]
References _data, _raw, _size, olsr::net::IPv6Address::address_size, olsr::net::IPv6Address::dump(), min_length, olsr::utl::Data::raw(), and olsr::pkt::Packet::raw::seqnum.
olsr::pkt::Packet::Packet (const address_t & addr, const utl::Data & d) [inline]
Member Function Documentation
::size_t olsr::pkt::Packet::size () const [inline]
References _size.
Referenced by olsr::net::RealInterface::shipout().
const utl::Data& olsr::pkt::Packet::data () const [inline]
References _data.
Referenced by olsr::sch::PacketReceiver::handle(), and olsr::net::RealInterface::send().
const address_t& olsr::pkt::Packet::sender () const [inline]
References _sender.
Referenced by olsr::sch::PacketReceiver::handle().
bool olsr::pkt::Packet::add_message (const msg::Message & m) [inline]
References _data, _sender, _size, and olsr::msg::Message::dump().
void olsr::pkt::Packet::close (const address_t & i) [inline]
References _data, _raw, _size, olsr::net::IPv6Address::address_size, olsr::utl::Data_< Self >::fit(), olsr::pkt::Packet::raw::length, min_length, olsr::pkt::Packet::raw::seqnum, and seqnum_map.
void olsr::pkt::Packet::parse (utl::Data d, const address_t & sender, const address_t & receiver) [inline, static]
References olsr::cproxy, olsr::sch::Scheduler::erase(), olsr::cst::hello_grace, olsr::utl::TimeVal::in(), olsr::sch::Scheduler::insert(), olsr::pkt::Packet::raw::length, olsr::set::CoherenceProxy::linkset(), olsr::main_addr, olsr::alg::main_addr_of(), olsr::set::Link::make_key(), olsr::msg::Message::min_length, min_length, olsr::msg::Message::parse(), olsr::utl::Data::raw(), olsr::scheduler, olsr::pkt::Packet::raw::seqnum, olsr::sch::TimedEvent::set_next(), olsr::utl::Data_< Self >::shrink_to(), olsr::msg::Message::raw::size, olsr::utl::Data_< Self >::size(), and olsr::warning.
Referenced by olsr::sch::PacketReceiver::handle().
Member Data Documentation
const ::size_t olsr::pkt::Packet::min_length = sizeof (raw) [static]
Referenced by close(), Packet(), parse(), and olsr::set::InterfaceSet::send_messages().
::size_t olsr::pkt::Packet::_size [private]
Referenced by add_message(), close(), Packet(), and size().
address_t olsr::pkt::Packet::_sender [private]
Referenced by add_message(), and sender().
utl::Data olsr::pkt::Packet::_data [private]
Referenced by add_message(), close(), data(), and Packet().
raw* olsr::pkt::Packet::_raw [private]
Referenced by close(), and Packet().
std::map< address_t, utl::Seqnum< u_int16_t > > olsr::pkt::Packet::seqnum_map = std::map<address_t, utl::Seqnum<u_int16_t> >() [static, protected]
Referenced by close().
The documentation for this class was generated from the following files:
packet.hh
packet.hxx