Qolyester daemon: olsr::sys::netlink::NLSocket Class Reference
olsr::sys::netlink::NLSocket Class Reference
#include <netlink.hh>
Public Types
typedef std::list< NLMessage * > answer_t
Public Member Functions
NLSocket ()
~NLSocket ()
void send (const NLMessage &m)
answer_t receive ()
Private Types
typedef sockaddr_nl sockaddr_t
Private Member Functions
void do_receive (char *&buffer, unsigned &length)
Private Attributes
int _fd
Member Typedef Documentation
typedef sockaddr_nl olsr::sys::netlink::NLSocket::sockaddr_t [private]
typedef std::list<NLMessage*> olsr::sys::netlink::NLSocket::answer_t
Constructor & Destructor Documentation
olsr::sys::netlink::NLSocket::NLSocket () [inline]
References _fd.
olsr::sys::netlink::NLSocket::~NLSocket () [inline]
References _fd.
Member Function Documentation
void olsr::sys::netlink::NLSocket::send (const NLMessage & m) [inline]
References _fd, olsr::sys::netlink::NLMessage::accept(), olsr::sys::netlink::RequestVisitor::buffer(), and olsr::sys::netlink::RequestVisitor::length().
Referenced by olsr::sys::internal::RoutingSocket::add_addr(), olsr::sys::internal::RoutingSocket::add_local_route(), olsr::sys::internal::RoutingSocket::add_remote_route(), olsr::sys::internal::RoutingSocket::del_addr(), olsr::sys::internal::RoutingSocket::print_kernel_routes(), olsr::sys::internal::RoutingSocket::remove_local_route(), olsr::sys::internal::RoutingSocket::remove_old_routes(), and olsr::sys::internal::RoutingSocket::remove_remote_route().
void olsr::sys::netlink::NLSocket::do_receive (char *& buffer, unsigned & length) [inline, private]
References _fd.
Referenced by receive().
std::list< NLMessage * > olsr::sys::netlink::NLSocket::receive () [inline]
References olsr::sys::netlink::NLNewRoute::add_attr(), olsr::sys::netlink::NLNewAddr::add_attr(), olsr::sys::netlink::NLNewLink::add_attr(), and do_receive().
Referenced by olsr::sys::internal::RoutingSocket::add_addr(), olsr::sys::internal::RoutingSocket::add_local_route(), olsr::sys::internal::RoutingSocket::add_remote_route(), olsr::sys::internal::RoutingSocket::del_addr(), olsr::sys::internal::RoutingSocket::print_kernel_routes(), olsr::sys::internal::RoutingSocket::remove_local_route(), olsr::sys::internal::RoutingSocket::remove_old_routes(), and olsr::sys::internal::RoutingSocket::remove_remote_route().
Member Data Documentation
int olsr::sys::netlink::NLSocket::_fd [private]
Referenced by do_receive(), NLSocket(), send(), and ~NLSocket().
The documentation for this class was generated from the following files:
netlink.hh
netlink.hxx