Qolyester daemon: olsr::sch::TimedEvent Class Reference
olsr::sch::TimedEvent Class Reference
Timed event abstract class.
#include <scheduler.hh>
Public Member Functions
TimedEvent (const timeval_t &n)
virtual ~TimedEvent ()
const timeval_t & next () const
void set_next (const timeval_t &n)
Protected Attributes
timeval_t next_
Next time of triggering.
Private Types
typedef TimedEvent This
typedef Event Super
Detailed Description
Timed event abstract class.
Member Typedef Documentation
typedef TimedEvent olsr::sch::TimedEvent::This [private]
Reimplemented in olsr::sch::MessageSender< M >, olsr::sch::MessageSender< msg::TCMessage >, olsr::sch::MessageForwarder, olsr::sch::StatePrinter, olsr::sch::UpdateEvent< F >, olsr::sch::PeriodicEvent_< I >, olsr::sch::JitteredEvent, and olsr::sch::PeriodicEvent_< olsr::sch::internal::JitterIncrement >.
typedef Event olsr::sch::TimedEvent::Super [private]
Reimplemented in olsr::sch::MessageSender< M >, olsr::sch::MessageSender< msg::TCMessage >, olsr::sch::MessageForwarder, olsr::sch::StatePrinter, olsr::sch::UpdateEvent< F >, olsr::sch::PeriodicEvent_< I >, olsr::sch::JitteredEvent, and olsr::sch::PeriodicEvent_< olsr::sch::internal::JitterIncrement >.
Constructor & Destructor Documentation
olsr::sch::TimedEvent::TimedEvent (const timeval_t & n) [inline]
Constructor.
next time of next triggering
h pointer to handler object
virtual olsr::sch::TimedEvent::~TimedEvent () [inline, virtual]
Destructor.
Member Function Documentation
const timeval_t& olsr::sch::TimedEvent::next () const [inline]
Next iteration accessor.
Returns:
reference to next time of triggering
References next_.
Referenced by olsr::sch::Scheduler::erase(), olsr::sch::Scheduler::handle_tevents(), olsr::sch::Scheduler::insert(), and olsr::sch::Scheduler::tevent_less::operator()().
void olsr::sch::TimedEvent::set_next (const timeval_t & n) [inline]
References next_.
Referenced by olsr::set::TwoHopNeighborSet::insert(), olsr::set::MIDSet::insert(), olsr::set::HNASet::insert(), olsr::set::DuplicateSet::insert(), olsr::set::CoherenceProxy::insert_link(), olsr::set::upd::LinkUpdater::operator()(), olsr::sch::QolyesterLoopHandler::operator()(), olsr::msg::TCMessage::parse(), olsr::pkt::Packet::parse(), and olsr::set::CoherenceProxy::set_mprsel().
Member Data Documentation
timeval_t olsr::sch::TimedEvent::next_ [protected]
Next time of triggering.
Referenced by olsr::sch::PeriodicEvent_< I >::handle(), next(), and set_next().
The documentation for this class was generated from the following file:
scheduler.hh