Qolyester daemon: olsr::sys::netlink::RequestVisitor Class Reference
olsr::sys::netlink::RequestVisitor Class Reference
#include <netlink.hh>
Public Member Functions
RequestVisitor ()
~RequestVisitor ()
virtual void visit (const NLGetLink &)
virtual void visit (const NLNewAddr &)
virtual void visit (const NLGetAddr &)
virtual void visit (const NLDelAddr &)
virtual void visit (const NLGetRoute &)
virtual void visit (const NLNewRoute &)
virtual void visit (const NLDelRoute &)
virtual void visit (const NLAddrAttrAddress &)
virtual void visit (const NLAddrAttrLocal &)
virtual void visit (const NLAddrAttrBroadcast &)
virtual void visit (const NLAddrAttrAnycast &)
virtual void visit (const NLRouteAttrDestination &)
virtual void visit (const NLRouteAttrGateway &)
virtual void visit (const NLRouteAttrOutInterface &)
const char * buffer ()
const unsigned length ()
Static Public Attributes
static unsigned seqnum = time(NULL)
Private Types
typedef std::list< iovec > buffers_t
Private Member Functions
unsigned totalsize () const
Private Attributes
buffers_t _buffers
char * _buffer
unsigned _length
Member Typedef Documentation
typedef std::list<iovec> olsr::sys::netlink::RequestVisitor::buffers_t [private]
Constructor & Destructor Documentation
olsr::sys::netlink::RequestVisitor::RequestVisitor () [inline]
olsr::sys::netlink::RequestVisitor::~RequestVisitor () [inline]
References _buffer, and _buffers.
Member Function Documentation
void olsr::sys::netlink::RequestVisitor::visit (const NLGetLink &) [inline, virtual]
References PREPARE_MESSAGE_GET, and SHIPOUT_MESSAGE.
void olsr::sys::netlink::RequestVisitor::visit (const NLNewAddr & e) [inline, virtual]
References olsr::sys::netlink::NLNewAddr::attrs(), olsr::sys::netlink::NLNewAddr::family(), olsr::sys::netlink::NLNewAddr::flags(), olsr::sys::netlink::NLNewAddr::index(), olsr::sys::netlink::NLNewAddr::prefixlen(), PREPARE_MESSAGE_NEW, olsr::sys::netlink::NLNewAddr::scope(), and SHIPOUT_MESSAGE.
void olsr::sys::netlink::RequestVisitor::visit (const NLGetAddr & e) [inline, virtual]
References olsr::sys::netlink::NLGetAddr::family(), PREPARE_MESSAGE_GET, and SHIPOUT_MESSAGE.
void olsr::sys::netlink::RequestVisitor::visit (const NLDelAddr & e) [inline, virtual]
References olsr::sys::netlink::NLDelAddr::attrs(), olsr::sys::netlink::NLDelAddr::family(), olsr::sys::netlink::NLDelAddr::flags(), olsr::sys::netlink::NLDelAddr::index(), olsr::sys::netlink::NLDelAddr::prefixlen(), PREPARE_MESSAGE_DEL, olsr::sys::netlink::NLDelAddr::scope(), and SHIPOUT_MESSAGE.
void olsr::sys::netlink::RequestVisitor::visit (const NLGetRoute & e) [inline, virtual]
References olsr::sys::netlink::NLGetRoute::family(), PREPARE_MESSAGE_GET, and SHIPOUT_MESSAGE.
void olsr::sys::netlink::RequestVisitor::visit (const NLNewRoute & e) [inline, virtual]
References olsr::sys::netlink::NLNewRoute::attrs(), olsr::sys::netlink::NLNewRoute::dlen(), olsr::sys::netlink::NLNewRoute::family(), olsr::sys::netlink::NLNewRoute::flags(), PREPARE_MESSAGE_NEW, olsr::sys::netlink::NLNewRoute::proto(), olsr::sys::netlink::NLNewRoute::scope(), SHIPOUT_MESSAGE, olsr::sys::netlink::NLNewRoute::slen(), olsr::sys::netlink::NLNewRoute::table(), olsr::sys::netlink::NLNewRoute::tos(), and olsr::sys::netlink::NLNewRoute::type().
void olsr::sys::netlink::RequestVisitor::visit (const NLDelRoute & e) [inline, virtual]
References olsr::sys::netlink::NLDelRoute::attrs(), olsr::sys::netlink::NLDelRoute::dlen(), olsr::sys::netlink::NLDelRoute::family(), olsr::sys::netlink::NLDelRoute::flags(), PREPARE_MESSAGE_DEL, olsr::sys::netlink::NLDelRoute::proto(), olsr::sys::netlink::NLDelRoute::scope(), SHIPOUT_MESSAGE, olsr::sys::netlink::NLDelRoute::slen(), olsr::sys::netlink::NLDelRoute::table(), olsr::sys::netlink::NLDelRoute::tos(), and olsr::sys::netlink::NLDelRoute::type().
void olsr::sys::netlink::RequestVisitor::visit (const NLAddrAttrAddress & e) [inline, virtual]
References _buffers, buffer(), olsr::sys::netlink::NLAddrAttrAddress::bytes(), and olsr::sys::netlink::NLAddrAttrAddress::length().
void olsr::sys::netlink::RequestVisitor::visit (const NLAddrAttrLocal & e) [inline, virtual]
References _buffers, buffer(), olsr::sys::netlink::NLAddrAttrLocal::bytes(), and olsr::sys::netlink::NLAddrAttrLocal::length().
void olsr::sys::netlink::RequestVisitor::visit (const NLAddrAttrBroadcast & e) [inline, virtual]
References _buffers, buffer(), olsr::sys::netlink::NLAddrAttrBroadcast::bytes(), and olsr::sys::netlink::NLAddrAttrBroadcast::length().
void olsr::sys::netlink::RequestVisitor::visit (const NLAddrAttrAnycast & e) [inline, virtual]
References _buffers, buffer(), olsr::sys::netlink::NLAddrAttrAnycast::bytes(), and olsr::sys::netlink::NLAddrAttrAnycast::length().
void olsr::sys::netlink::RequestVisitor::visit (const NLRouteAttrDestination & e) [inline, virtual]
References _buffers, buffer(), olsr::sys::netlink::NLRouteAttrDestination::bytes(), and olsr::sys::netlink::NLRouteAttrDestination::length().
void olsr::sys::netlink::RequestVisitor::visit (const NLRouteAttrGateway & e) [inline, virtual]
References _buffers, buffer(), olsr::sys::netlink::NLRouteAttrGateway::bytes(), and olsr::sys::netlink::NLRouteAttrGateway::length().
void olsr::sys::netlink::RequestVisitor::visit (const NLRouteAttrOutInterface & e) [inline, virtual]
References _buffers, buffer(), and olsr::sys::netlink::NLRouteAttrOutInterface::index().
const char * olsr::sys::netlink::RequestVisitor::buffer () [inline]
References _buffer, _buffers, _length, and totalsize().
Referenced by length(), olsr::sys::netlink::NLSocket::send(), and visit().
const unsigned olsr::sys::netlink::RequestVisitor::length () [inline]
References _buffer, _length, and buffer().
Referenced by olsr::sys::netlink::NLSocket::send().
unsigned olsr::sys::netlink::RequestVisitor::totalsize () const [private]
References _buffers.
Referenced by buffer().
Member Data Documentation
unsigned olsr::sys::netlink::RequestVisitor::seqnum = time(NULL) [static]
buffers_t olsr::sys::netlink::RequestVisitor::_buffers [private]
Referenced by buffer(), totalsize(), visit(), and ~RequestVisitor().
char* olsr::sys::netlink::RequestVisitor::_buffer [private]
Referenced by buffer(), length(), and ~RequestVisitor().
unsigned olsr::sys::netlink::RequestVisitor::_length [private]
Referenced by buffer(), and length().
The documentation for this class was generated from the following files:
netlink.hh
netlink.hxx