Qolyester daemon: olsr::sys::netlink::NLDelRoute Class Reference
olsr::sys::netlink::NLDelRoute Class Reference
#include <netlink.hh>
Public Types
typedef std::list< NLRouteAttr * > attrs_t
Public Member Functions
NLDelRoute (unsigned char f, unsigned char dlen, unsigned char slen, unsigned char tos, unsigned char table, unsigned char proto, unsigned char scope, unsigned char type, unsigned int flags)
virtual ~NLDelRoute ()
virtual void accept (Visitor &v) const
unsigned char family () const
unsigned char dlen () const
unsigned char slen () const
unsigned char tos () const
unsigned char table () const
unsigned char proto () const
unsigned char scope () const
unsigned char type () const
unsigned int flags () const
const attrs_t & attrs () const
attrs_t & attrs ()
void add_attr (NLRouteAttr *a)
Private Attributes
unsigned char _family
unsigned char _dlen
unsigned char _slen
unsigned char _tos
unsigned char _table
unsigned char _proto
unsigned char _scope
unsigned char _type
unsigned int _flags
attrs_t _attrs
Member Typedef Documentation
typedef std::list<NLRouteAttr*> olsr::sys::netlink::NLDelRoute::attrs_t
Constructor & Destructor Documentation
olsr::sys::netlink::NLDelRoute::NLDelRoute (unsigned char f, unsigned char dlen, unsigned char slen, unsigned char tos, unsigned char table, unsigned char proto, unsigned char scope, unsigned char type, unsigned int flags) [inline]
virtual olsr::sys::netlink::NLDelRoute::~NLDelRoute () [inline, virtual]
References _attrs.
Member Function Documentation
virtual void olsr::sys::netlink::NLDelRoute::accept (Visitor & v) const [inline, virtual]
Implements olsr::sys::netlink::NLMessage.
unsigned char olsr::sys::netlink::NLDelRoute::family () const [inline]
References _family.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
unsigned char olsr::sys::netlink::NLDelRoute::dlen () const [inline]
References _dlen.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
unsigned char olsr::sys::netlink::NLDelRoute::slen () const [inline]
References _slen.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
unsigned char olsr::sys::netlink::NLDelRoute::tos () const [inline]
References _tos.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
unsigned char olsr::sys::netlink::NLDelRoute::table () const [inline]
References _table.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
unsigned char olsr::sys::netlink::NLDelRoute::proto () const [inline]
References _proto.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
unsigned char olsr::sys::netlink::NLDelRoute::scope () const [inline]
References _scope.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
unsigned char olsr::sys::netlink::NLDelRoute::type () const [inline]
References _type.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
unsigned int olsr::sys::netlink::NLDelRoute::flags () const [inline]
References _flags.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
const attrs_t& olsr::sys::netlink::NLDelRoute::attrs () const [inline]
References _attrs.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
attrs_t& olsr::sys::netlink::NLDelRoute::attrs () [inline]
References _attrs.
void olsr::sys::netlink::NLDelRoute::add_attr (NLRouteAttr * a) [inline]
References _attrs.
Member Data Documentation
unsigned char olsr::sys::netlink::NLDelRoute::_family [private]
Referenced by family().
unsigned char olsr::sys::netlink::NLDelRoute::_dlen [private]
Referenced by dlen().
unsigned char olsr::sys::netlink::NLDelRoute::_slen [private]
Referenced by slen().
unsigned char olsr::sys::netlink::NLDelRoute::_tos [private]
Referenced by tos().
unsigned char olsr::sys::netlink::NLDelRoute::_table [private]
Referenced by table().
unsigned char olsr::sys::netlink::NLDelRoute::_proto [private]
Referenced by proto().
unsigned char olsr::sys::netlink::NLDelRoute::_scope [private]
Referenced by scope().
unsigned char olsr::sys::netlink::NLDelRoute::_type [private]
Referenced by type().
unsigned int olsr::sys::netlink::NLDelRoute::_flags [private]
Referenced by flags().
attrs_t olsr::sys::netlink::NLDelRoute::_attrs [private]
Referenced by add_attr(), attrs(), and ~NLDelRoute().
The documentation for this class was generated from the following file:
netlink.hh