Qolyester daemon: olsr::sys::RoutingActions Class Reference
olsr::sys::RoutingActions Class Reference
#include <routing.hh>
Public Member Functions
void print_kernel_routes ()
void remove_old_routes ()
void add_local_route (const net::LocalRoute &r)
void add_remote_route (const net::RemoteRoute &r)
void remove_local_route (const net::LocalRoute &r)
void remove_remote_route (const net::RemoteRoute &r)
Private Attributes
internal::RoutingSocket _rs
Member Function Documentation
void olsr::sys::RoutingActions::print_kernel_routes () [inline]
References _rs, and olsr::sys::internal::RoutingSocket::print_kernel_routes().
Referenced by olsr::alg::flush_routes().
void olsr::sys::RoutingActions::remove_old_routes () [inline]
References _rs, olsr::error, and olsr::sys::internal::RoutingSocket::remove_old_routes().
Referenced by olsr::alg::clean_routes().
void olsr::sys::RoutingActions::add_local_route (const net::LocalRoute & r) [inline]
References _rs, olsr::sys::internal::RoutingSocket::add_local_route(), olsr::net::LocalRoute::dest_addr(), olsr::error, olsr::net::LocalRoute::interface_info(), and olsr::net::LocalRoute::prefix().
Referenced by olsr::alg::flush_routes().
void olsr::sys::RoutingActions::add_remote_route (const net::RemoteRoute & r) [inline]
References _rs, olsr::sys::internal::RoutingSocket::add_remote_route(), olsr::net::RemoteRoute::dest_addr(), olsr::error, olsr::net::RemoteRoute::next_addr(), and olsr::net::RemoteRoute::prefix().
Referenced by olsr::alg::flush_routes().
void olsr::sys::RoutingActions::remove_local_route (const net::LocalRoute & r) [inline]
References _rs, olsr::net::LocalRoute::dest_addr(), olsr::error, olsr::net::LocalRoute::interface_info(), olsr::net::LocalRoute::prefix(), and olsr::sys::internal::RoutingSocket::remove_local_route().
Referenced by olsr::alg::flush_routes().
void olsr::sys::RoutingActions::remove_remote_route (const net::RemoteRoute & r) [inline]
References _rs, olsr::net::RemoteRoute::dest_addr(), olsr::error, olsr::net::RemoteRoute::next_addr(), olsr::net::RemoteRoute::prefix(), and olsr::sys::internal::RoutingSocket::remove_remote_route().
Referenced by olsr::alg::flush_routes().
Member Data Documentation
internal::RoutingSocket olsr::sys::RoutingActions::_rs [private]
Referenced by add_local_route(), add_remote_route(), print_kernel_routes(), remove_local_route(), remove_old_routes(), and remove_remote_route().
The documentation for this class was generated from the following files:
routing.hh
routing.hxx