Qolyester daemon: olsr::msg::TCMessage Class Reference
olsr::msg::TCMessage Class Reference
TC message class.
#include <tc.hh>
Public Member Functions
TCMessage ()
TCMessage (const utl::Data &)
virtual ~TCMessage ()
virtual bool dump (utl::Data &, const address_t &) const
Static Public Member Functions
static void parse (const utl::ConstData &, const Message::header &)
Static Public Attributes
static const ::size_t min_length = sizeof (raw)
Minimum length of a TC message.
Private Attributes
utl::Data _data
The message data buffer.
Classes
struct raw
Convenience definition of the TC header.
Detailed Description
TC message class.
Constructor & Destructor Documentation
olsr::msg::TCMessage::TCMessage () [inline]
The default constructor
olsr::msg::TCMessage::TCMessage (const utl::Data & d) [inline]
The constructor
d Message data buffer
virtual olsr::msg::TCMessage::~TCMessage () [inline, virtual]
The destructor
Member Function Documentation
bool olsr::msg::TCMessage::dump (utl::Data & d, const address_t & interface) const [inline, virtual]
The dumping method
d Destination data buffer
interface Source interface address of the packet
Returns:
true if the message is to be sent again
Implements olsr::msg::Message.
References _data, olsr::msg::Message::raw::addr, ADDRESS_SIZE, olsr::set::CoherenceProxy::advset_seqnum(), olsr::cproxy, olsr::msg::Message::raw::data, olsr::do_dump_tc, olsr::utl::Data_< Self >::dump(), olsr::net::IPv6Address::dump(), olsr::dump_tc, olsr::utl::Data_< Self >::empty(), olsr::msg::Message::raw::hopcount, olsr::utl::TimeVal::in(), olsr::set::CoherenceProxy::is_advset_empty(), olsr::main_addr, min_length, olsr::msg::Message::min_length, olsr::utl::TimeVal::now(), olsr::utl::Data::raw(), olsr::msg::Message::raw::seqnum, olsr::msg::Message::seqnum, olsr::msg::Message::raw::size, olsr::utl::Data_< Self >::size(), olsr::set::CoherenceProxy::stamp_hold(), olsr::cst::tc_interval, TC_MESSAGE, olsr::set::CoherenceProxy::tc_neighborset(), olsr::tc_redundancy, olsr::cst::top_hold_time, olsr::msg::Message::raw::ttl, olsr::msg::Message::raw::type, and olsr::msg::Message::raw::vtime.
void olsr::msg::TCMessage::parse (const utl::ConstData & d, const Message::header & mh) [inline, static]
The parsing routine
d Message data buffer
mh Message header
References ADDRESS_SIZE, olsr::cproxy, olsr::do_dump_tc, olsr::dump_tc, olsr::sch::Scheduler::erase(), olsr::set::TopologySet::erase(), olsr::msg::Message::header::hopcount, olsr::utl::TimeVal::in(), olsr::set::TopologySet::insert(), olsr::sch::Scheduler::insert(), olsr::set::CoherenceProxy::linkset(), olsr::main_addr, olsr::set::Link::make_key(), olsr::msg::Message::header::mseqnum, olsr::msg::Message::header::originator, olsr::msg::Message::header::pseqnum, olsr::utl::Data_< Self >::raw(), olsr::msg::Message::header::receiver, olsr::scheduler, olsr::msg::Message::header::sender, olsr::sch::TimedEvent::set_next(), olsr::utl::Data_< Self >::size(), olsr::topo_set, olsr::set::TopologySet::toposet(), and olsr::msg::Message::header::validity.
Referenced by olsr::msg::Message::parse().
Member Data Documentation
const ::size_t olsr::msg::TCMessage::min_length = sizeof (raw) [static]
Minimum length of a TC message.
Reimplemented from olsr::msg::Message.
Referenced by dump().
utl::Data olsr::msg::TCMessage::_data [private]
The message data buffer.
Referenced by dump().
The documentation for this class was generated from the following files:
tc.hh
tc.hxx