Qolyester daemon: olsr::sys::RealInterfaceInfo Class Reference
olsr::sys::RealInterfaceInfo Class Reference
#include <realinterfaceinfo.hh>
Public Types
typedef
sys::internal::InterfaceConfig config_t
Public Member Functions
RealInterfaceInfo ()
RealInterfaceInfo (const std::string &name)
This & operator= (const This &other)
const std::string & name () const
unsigned mtu () const
unsigned index () const
const address_t & get_addr () const
const address_t & get_addr (const address_t &) const
const address_t get_bcast (const address_t &) const
unsigned get_prefix (const address_t &) const
void add_addr (const address_t &, unsigned)
void del_addr (const address_t &)
Package Types
typedef std::set< addr_t > addrs_t
Package Attributes
__pad0__:InterfaceAddress addr_t
Private Types
typedef RealInterfaceInfo This
Private Attributes
const std::string _name
unsigned _mtu
unsigned _index
addrs_t _addrs
Member Typedef Documentation
typedef RealInterfaceInfo olsr::sys::RealInterfaceInfo::This [private]
typedef std::set<addr_t> olsr::sys::RealInterfaceInfo::addrs_t [package]
typedef sys::internal::InterfaceConfig olsr::sys::RealInterfaceInfo::config_t
Constructor & Destructor Documentation
olsr::sys::RealInterfaceInfo::RealInterfaceInfo () [inline]
Referenced by add_addr(), and del_addr().
olsr::sys::RealInterfaceInfo::RealInterfaceInfo (const std::string & name) [inline, explicit]
References _addrs, _index, _mtu, olsr::sys::internal::InterfaceInfo::addrs(), olsr::sys::internal::InterfaceInfo::index(), and olsr::sys::internal::InterfaceInfo::mtu().
Member Function Documentation
RealInterfaceInfo & olsr::sys::RealInterfaceInfo::operator= (const This & other) [inline]
References _addrs, _index, _mtu, and _name.
const std::string& olsr::sys::RealInterfaceInfo::name () const [inline]
References _name.
Referenced by olsr::sys::internal::RoutingSocket::add_local_route(), olsr::sys::Socket::bind_multicast(), olsr::net::RealInterface::RealInterface(), olsr::sys::internal::RoutingSocket::remove_local_route(), olsr::sys::Socket::set_multicast(), and olsr::net::RealInterface::shipout().
unsigned olsr::sys::RealInterfaceInfo::mtu () const [inline]
References _mtu.
Referenced by olsr::net::RealInterface::mtu(), and olsr::net::RealInterface::RealInterface().
unsigned olsr::sys::RealInterfaceInfo::index () const [inline]
References _index.
Referenced by olsr::sys::internal::RoutingSocket::add_local_route(), olsr::sys::Socket::bind_multicast(), olsr::net::LocalRoute::LocalRoute(), olsr::net::LocalRoute::operator==(), olsr::net::RealInterface::RealInterface(), olsr::sys::internal::RoutingSocket::remove_local_route(), and olsr::sys::Socket::set_multicast().
const address_t & olsr::sys::RealInterfaceInfo::get_addr () const [inline]
References _addrs, _name, ADDRESS_SIZE, and olsr::net::IPv6Address::is_linklocal().
const address_t & olsr::sys::RealInterfaceInfo::get_addr (const address_t & a) const [inline]
References _addrs, _name, and olsr::net::IPv6Address::to_string().
const address_t olsr::sys::RealInterfaceInfo::get_bcast (const address_t & a) const [inline]
References _addrs, and olsr::net::IPv6Address::is_linklocal().
Referenced by olsr::net::RealInterface::RealInterface().
unsigned olsr::sys::RealInterfaceInfo::get_prefix (const address_t & a) const [inline]
References _addrs.
void olsr::sys::RealInterfaceInfo::add_addr (const address_t & a, unsigned p) [inline]
References _index, _name, and RealInterfaceInfo().
void olsr::sys::RealInterfaceInfo::del_addr (const address_t & a) [inline]
References _addrs, _index, _name, olsr::set::InterfaceSet::end(), olsr::set::InterfaceSet::find(), olsr::iface_set, RealInterfaceInfo(), and olsr::net::IPv6Address::to_string().
Member Data Documentation
olsr::sys::RealInterfaceInfo::__pad0__ [package]
const std::string olsr::sys::RealInterfaceInfo::_name [private]
Referenced by add_addr(), del_addr(), get_addr(), name(), and operator=().
unsigned olsr::sys::RealInterfaceInfo::_mtu [private]
Referenced by mtu(), operator=(), and RealInterfaceInfo().
unsigned olsr::sys::RealInterfaceInfo::_index [private]
Referenced by add_addr(), del_addr(), index(), operator=(), and RealInterfaceInfo().
addrs_t olsr::sys::RealInterfaceInfo::_addrs [private]
Referenced by del_addr(), get_addr(), get_bcast(), get_prefix(), operator=(), and RealInterfaceInfo().
The documentation for this class was generated from the following files:
realinterfaceinfo.hh
realinterfaceinfo.hxx