Qolyester daemon: olsr::sch::PeriodicEvent_< I > Class Template Reference
olsr::sch::PeriodicEvent_< I > Class Template Reference
#include <scheduler.hh>
Public Member Functions
PeriodicEvent_ (const timeval_t &n, const timeval_t &p)
PeriodicEvent_ (const timeval_t &n, const timeval_t &p, const I &i)
virtual void handle ()
Private Types
typedef PeriodicEvent_< I > This
typedef TimedEvent Super
Private Attributes
timeval_t period_
I increment_
template<class I = internal::TrivialIncrement>
class olsr::sch::PeriodicEvent_< I >
Member Typedef Documentation
template<class I = internal::TrivialIncrement> typedef PeriodicEvent_<I> olsr::sch::PeriodicEvent_< I >::This [private]
Reimplemented from olsr::sch::TimedEvent.
Reimplemented in olsr::sch::MessageSender< M >, olsr::sch::MessageSender< msg::TCMessage >, olsr::sch::StatePrinter, and olsr::sch::JitteredEvent.
template<class I = internal::TrivialIncrement> typedef TimedEvent olsr::sch::PeriodicEvent_< I >::Super [private]
Reimplemented from olsr::sch::TimedEvent.
Reimplemented in olsr::sch::MessageSender< M >, olsr::sch::MessageSender< msg::TCMessage >, olsr::sch::StatePrinter, and olsr::sch::JitteredEvent.
Constructor & Destructor Documentation
template<class I = internal::TrivialIncrement> olsr::sch::PeriodicEvent_< I >::PeriodicEvent_ (const timeval_t & n, const timeval_t & p) [inline]
template<class I = internal::TrivialIncrement> olsr::sch::PeriodicEvent_< I >::PeriodicEvent_ (const timeval_t & n, const timeval_t & p, const I & i) [inline]
Member Function Documentation
template<class I> void olsr::sch::PeriodicEvent_< I >::handle () [inline, virtual]
Virtual handling method.
Implements olsr::sch::Event.
Reimplemented in olsr::sch::MessageSender< M >, olsr::sch::MessageSender< msg::TCMessage >, and olsr::sch::StatePrinter.
References olsr::sch::PeriodicEvent_< I >::increment_, olsr::sch::Scheduler::insert(), olsr::utl::TimeVal::is_past(), olsr::sch::TimedEvent::next_, olsr::sch::PeriodicEvent_< I >::period_, and olsr::scheduler.
Referenced by olsr::sch::StatePrinter::handle(), olsr::sch::MessageSender< msg::TCMessage >::handle(), and olsr::sch::MessageSender< M >::handle().
Member Data Documentation
template<class I = internal::TrivialIncrement> timeval_t olsr::sch::PeriodicEvent_< I >::period_ [private]
Referenced by olsr::sch::PeriodicEvent_< I >::handle().
template<class I = internal::TrivialIncrement> I olsr::sch::PeriodicEvent_< I >::increment_ [private]
Referenced by olsr::sch::PeriodicEvent_< I >::handle().
The documentation for this class was generated from the following files:
scheduler.hh
scheduler.hxx