Qolyester daemon: olsr::net::RemoteRoute Class Reference
olsr::net::RemoteRoute Class Reference
#include <route.hh>
Public Member Functions
RemoteRoute (const address_t &d, unsigned p, const address_t &n)
RemoteRoute (const This &other)
const address_t & dest_addr () const
unsigned prefix () const
const address_t & next_addr () const
bool operator== (const This &rhs) const
Static Public Member Functions
static const This & make_key (const address_t &d, unsigned p)
Private Types
typedef RemoteRoute This
Private Member Functions
RemoteRoute ()
Private Attributes
const address_t _d_addr
const unsigned _prefix
const address_t _n_addr
Static Private Attributes
static This _dummy_for_find
Member Typedef Documentation
typedef RemoteRoute olsr::net::RemoteRoute::This [private]
Constructor & Destructor Documentation
olsr::net::RemoteRoute::RemoteRoute () [explicit, private]
olsr::net::RemoteRoute::RemoteRoute (const address_t & d, unsigned p, const address_t & n) [inline]
References _n_addr.
olsr::net::RemoteRoute::RemoteRoute (const This & other) [inline]
References _n_addr.
Member Function Documentation
const address_t& olsr::net::RemoteRoute::dest_addr () const [inline]
References _d_addr.
Referenced by olsr::sys::RoutingActions::add_remote_route(), olsr::net::hash_RemoteRoute::operator()(), and olsr::sys::RoutingActions::remove_remote_route().
unsigned olsr::net::RemoteRoute::prefix () const [inline]
References _prefix.
Referenced by olsr::sys::RoutingActions::add_remote_route(), and olsr::sys::RoutingActions::remove_remote_route().
const address_t& olsr::net::RemoteRoute::next_addr () const [inline]
References _n_addr.
Referenced by olsr::sys::RoutingActions::add_remote_route(), and olsr::sys::RoutingActions::remove_remote_route().
bool olsr::net::RemoteRoute::operator== (const This & rhs) const [inline]
References _d_addr, _n_addr, and _prefix.
const RemoteRoute & olsr::net::RemoteRoute::make_key (const address_t & d, unsigned p) [inline, static]
References _d_addr, _dummy_for_find, and _prefix.
Member Data Documentation
const address_t olsr::net::RemoteRoute::_d_addr [private]
Referenced by dest_addr(), make_key(), and operator==().
const unsigned olsr::net::RemoteRoute::_prefix [private]
Referenced by make_key(), operator==(), and prefix().
const address_t olsr::net::RemoteRoute::_n_addr [private]
Referenced by next_addr(), operator==(), and RemoteRoute().
This olsr::net::RemoteRoute::_dummy_for_find [static, private]
Referenced by make_key().
The documentation for this class was generated from the following files:
route.hh
route.hxx