Qolyester daemon: olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet > Class Template Reference
olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet > Class Template Reference
#include <set.hh>
Public Types
typedef Set::key_type key_type
typedef Set::value_type value_type
typedef Set::iterator set_iterator
typedef e_iterator_ mask_iterator
typedef m_iterator_ iterator
typedef iterator const_iterator
Public Member Functions
Subset (Set &s)
Subset (ActionSet &as, Set &s)
iterator begin (const key_type &k)
iterator end (const key_type &k)
void set_stamp (const_iterator pos, const TimeVal &now=TimeVal::now())
const TimeVal stamp (const_iterator pos) const
bool expired (const_iterator pos, const TimeVal &period, const TimeVal &now=TimeVal::now()) const
Private Types
typedef Subset< MSAdapt< Set >
, Action, Predicate, ActionSet > This
typedef MaskIterator< MSAdapt
< Set >, Action, Predicate,
ActionSet > e_iterator_
typedef DeconstIterator
< e_iterator_ > m_iterator_
Private Attributes
ActionSet & actionset_
Set & set_
template<class Set, class Action, class Predicate, class ActionSet>
class olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >
Member Typedef Documentation
template<class Set, class Action, class Predicate, class ActionSet> typedef Subset<MSAdapt<Set>, Action, Predicate, ActionSet> olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::This [private]
template<class Set, class Action, class Predicate, class ActionSet> typedef MaskIterator<MSAdapt<Set>, Action, Predicate, ActionSet> olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::e_iterator_ [private]
template<class Set, class Action, class Predicate, class ActionSet> typedef DeconstIterator<e_iterator_> olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::m_iterator_ [private]
template<class Set, class Action, class Predicate, class ActionSet> typedef Set::key_type olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::key_type
template<class Set, class Action, class Predicate, class ActionSet> typedef Set::value_type olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::value_type
template<class Set, class Action, class Predicate, class ActionSet> typedef Set::iterator olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::set_iterator
template<class Set, class Action, class Predicate, class ActionSet> typedef e_iterator_ olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::mask_iterator
template<class Set, class Action, class Predicate, class ActionSet> typedef m_iterator_ olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::iterator
template<class Set, class Action, class Predicate, class ActionSet> typedef iterator olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::const_iterator
Constructor & Destructor Documentation
template<class Set, class Action, class Predicate, class ActionSet> olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::Subset (Set & s) [inline]
template<class Set, class Action, class Predicate, class ActionSet> olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::Subset (ActionSet & as, Set & s) [inline]
Member Function Documentation
template<class Set, class Action, class Predicate, class ActionSet> iterator olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::begin (const key_type & k) [inline]
References olsr::utl::Subset< Set, Action, Predicate, ActionSet >::actionset_, olsr::utl::Set< Elem, Iset, Iter, CIter >::begin(), olsr::utl::DeconstIterator< Iter >::build(), and olsr::utl::Subset< Set, Action, Predicate, ActionSet >::set_.
template<class Set, class Action, class Predicate, class ActionSet> iterator olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::end (const key_type & k) [inline]
References olsr::utl::Subset< Set, Action, Predicate, ActionSet >::actionset_, olsr::utl::DeconstIterator< Iter >::build(), olsr::utl::Set< Elem, Iset, Iter, CIter >::end(), and olsr::utl::Subset< Set, Action, Predicate, ActionSet >::set_.
template<class Set, class Action, class Predicate, class ActionSet> void olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::set_stamp (const_iterator pos, const TimeVal & now = TimeVal::now()) [inline]
References olsr::utl::Subset< Set, Action, Predicate, ActionSet >::set_.
template<class Set, class Action, class Predicate, class ActionSet> const TimeVal olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::stamp (const_iterator pos) const [inline]
References olsr::utl::Subset< Set, Action, Predicate, ActionSet >::set_.
template<class Set, class Action, class Predicate, class ActionSet> bool olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::expired (const_iterator pos, const TimeVal & period, const TimeVal & now = TimeVal::now()) const [inline]
References olsr::utl::Subset< Set, Action, Predicate, ActionSet >::set_.
Member Data Documentation
template<class Set, class Action, class Predicate, class ActionSet> ActionSet& olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::actionset_ [private]
template<class Set, class Action, class Predicate, class ActionSet> Set& olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::set_ [private]
The documentation for this class was generated from the following file:
set.hh