Qolyester daemon: olsr::sch::PollEvent_< P > Class Template Reference
olsr::sch::PollEvent_< P > Class Template Reference
#include <scheduler.hh>
Public Types
typedef P p_t
Public Member Functions
PollEvent_ (const P &p)
virtual ~PollEvent_ ()
const P & p () const
P & p ()
Private Types
typedef PollEvent_< P > This
typedef Event Super
Private Attributes
P p_
template<class P = internal::PollData>
class olsr::sch::PollEvent_< P >
Member Typedef Documentation
template<class P = internal::PollData> typedef PollEvent_<P> olsr::sch::PollEvent_< P >::This [private]
Reimplemented in olsr::sch::PacketSender, and olsr::sch::PacketReceiver.
template<class P = internal::PollData> typedef Event olsr::sch::PollEvent_< P >::Super [private]
Reimplemented in olsr::sch::PacketSender, and olsr::sch::PacketReceiver.
template<class P = internal::PollData> typedef P olsr::sch::PollEvent_< P >::p_t
Constructor & Destructor Documentation
template<class P = internal::PollData> olsr::sch::PollEvent_< P >::PollEvent_ (const P & p) [inline]
template<class P = internal::PollData> virtual olsr::sch::PollEvent_< P >::~PollEvent_ () [inline, virtual]
Member Function Documentation
template<class P = internal::PollData> const P& olsr::sch::PollEvent_< P >::p () const [inline]
References olsr::sch::PollEvent_< P >::p_.
Referenced by olsr::sch::PacketReceiver::handle(), olsr::sch::PacketSender::handle(), olsr::sch::Scheduler::handle_ioevents(), olsr::sch::Scheduler::ioevent_less::operator()(), and olsr::sch::internal::PollData::poll().
template<class P = internal::PollData> P& olsr::sch::PollEvent_< P >::p () [inline]
References olsr::sch::PollEvent_< P >::p_.
Member Data Documentation
template<class P = internal::PollData> P olsr::sch::PollEvent_< P >::p_ [private]
Referenced by olsr::sch::PollEvent_< P >::p().
The documentation for this class was generated from the following file:
scheduler.hh