Qolyester daemon: olsr::sch::StatePrinter Class Reference
olsr::sch::StatePrinter Class Reference
#include <events.hh>
Public Member Functions
StatePrinter ()
virtual void handle ()
Private Types
typedef StatePrinter This
typedef PeriodicEvent Super
Member Typedef Documentation
typedef StatePrinter olsr::sch::StatePrinter::This [private]
Reimplemented from olsr::sch::PeriodicEvent_< I >.
typedef PeriodicEvent olsr::sch::StatePrinter::Super [private]
Reimplemented from olsr::sch::PeriodicEvent_< I >.
Constructor & Destructor Documentation
olsr::sch::StatePrinter::StatePrinter () [inline]
Member Function Documentation
void olsr::sch::StatePrinter::handle () [inline, virtual]
Virtual handling method.
Reimplemented from olsr::sch::PeriodicEvent_< I >.
References olsr::cproxy, olsr::debug, olsr::utl::deindent(), olsr::utl::down(), olsr::set::DuplicateSet::dset_, olsr::dump_state, olsr::dup_set, olsr::sch::PeriodicEvent_< I >::handle(), olsr::hna_set, olsr::set::HNASet::hset_, indent, olsr::lroute_set, olsr::set::CoherenceProxy::lset_, olsr::mid_set, olsr::set::MIDSet::mset_, olsr::utl::TimeVal::now(), olsr::set::CoherenceProxy::nset_, olsr::path_net, olsr::rroute_set, olsr::utl::Set< Elem, Iset, Iter, CIter >::set_, olsr::thn_set, olsr::topo_set, olsr::set::TopologySet::tset_, olsr::set::TwoHopNeighborSet::tset_, and olsr::utl::up().
The documentation for this class was generated from the following files:
events.hh
events.hxx