Qolyester daemon: olsr::set::TwoHopNeighborSet Class Reference
olsr::set::TwoHopNeighborSet Class Reference
#include <neighbors.hh>
Public Types
typedef val_tset_t thnset_t
Public Member Functions
thnset_t & thnset ()
TwoHopNeighborSet ()
virtual ~TwoHopNeighborSet ()
void insert (const TwoHopNeighbor &x)
void erase (const tset_t::iterator &pos)
void erase (const tset_t::value_type &x)
Private Types
typedef TwoHopNeighborSet This
typedef sch::Updatable
< TwoHopNeighbor > elem_t
typedef std::set< elem_t > tset_t
typedef sch::upd::SetEraser
< This, tset_t::iterator > eraser_t
typedef sch::UpdateEvent
< eraser_t > updater_t
typedef utl::Subset< tset_t,
utl::NoAction< This,
tset_t::iterator >
, utl::DefaultPredicate< This,
tset_t::iterator >, This > val_tset_t
Private Attributes
tset_t tset_
thnset_t thnset_
Friends
class sch::StatePrinter
Member Typedef Documentation
typedef TwoHopNeighborSet olsr::set::TwoHopNeighborSet::This [private]
typedef sch::Updatable<TwoHopNeighbor> olsr::set::TwoHopNeighborSet::elem_t [private]
typedef std::set<elem_t> olsr::set::TwoHopNeighborSet::tset_t [private]
typedef sch::upd::SetEraser<This, tset_t::iterator> olsr::set::TwoHopNeighborSet::eraser_t [private]
typedef sch::UpdateEvent<eraser_t> olsr::set::TwoHopNeighborSet::updater_t [private]
typedef utl::Subset<tset_t, utl::NoAction<This, tset_t::iterator>, utl::DefaultPredicate<This, tset_t::iterator>, This> olsr::set::TwoHopNeighborSet::val_tset_t [private]
typedef val_tset_t olsr::set::TwoHopNeighborSet::thnset_t
Constructor & Destructor Documentation
olsr::set::TwoHopNeighborSet::TwoHopNeighborSet () [inline]
virtual olsr::set::TwoHopNeighborSet::~TwoHopNeighborSet () [inline, virtual]
Member Function Documentation
thnset_t& olsr::set::TwoHopNeighborSet::thnset () [inline]
References thnset_.
Referenced by olsr::alg::mprselection().
void olsr::set::TwoHopNeighborSet::insert (const TwoHopNeighbor & x) [inline]
References olsr::cproxy, olsr::sch::Scheduler::erase(), olsr::sch::Scheduler::insert(), olsr::gra::AdjGraph::insert_arc(), olsr::gra::AdjGraph::insert_node(), olsr::set::TwoHopNeighbor::main_addr(), olsr::alg::main_addr_of(), olsr::set::Neighbor::make_key(), olsr::mprset_recomp, olsr::path_net, olsr::routes_recomp, olsr::scheduler, olsr::utl::Mark::set_mark(), olsr::sch::TimedEvent::set_next(), olsr::set::CoherenceProxy::sym_neighborset(), olsr::set::TwoHopNeighbor::time(), tset_, olsr::gra::twohop, and olsr::set::TwoHopNeighbor::twohop_addr().
Referenced by olsr::msg::HELLOMessage::parse().
void olsr::set::TwoHopNeighborSet::erase (const tset_t::iterator & pos) [inline]
References olsr::cproxy, olsr::sch::Scheduler::destroy(), olsr::gra::AdjNode::make_key(), olsr::gra::AdjInfo::make_key(), olsr::set::Neighbor::make_key(), olsr::mprset_recomp, olsr::path_net, olsr::gra::AdjGraph::remove_arc(), olsr::gra::AdjGraph::remove_node_if_alone(), olsr::routes_recomp, olsr::scheduler, olsr::utl::Mark::set_mark(), olsr::set::CoherenceProxy::sym_neighborset(), tset_, and olsr::gra::twohop.
Referenced by erase(), and olsr::msg::HELLOMessage::parse().
void olsr::set::TwoHopNeighborSet::erase (const tset_t::value_type & x) [inline]
References erase(), and tset_.
Friends And Related Function Documentation
friend class sch::StatePrinter [friend]
Member Data Documentation
tset_t olsr::set::TwoHopNeighborSet::tset_ [private]
Referenced by erase(), olsr::sch::StatePrinter::handle(), and insert().
thnset_t olsr::set::TwoHopNeighborSet::thnset_ [private]
Referenced by thnset().
The documentation for this class was generated from the following files:
neighbors.hh
neighbors.hxx