Qolyester daemon: olsr::sys::netlink::NLDelAddr Class Reference
olsr::sys::netlink::NLDelAddr Class Reference
#include <netlink.hh>
Public Types
typedef std::list< NLAddrAttr * > attrs_t
Public Member Functions
NLDelAddr (unsigned char f, unsigned char p, unsigned char fl, unsigned char s, int i)
virtual ~NLDelAddr ()
virtual void accept (Visitor &v) const
unsigned char family () const
unsigned char prefixlen () const
unsigned char flags () const
unsigned char scope () const
int index () const
const attrs_t & attrs () const
void add_attr (NLAddrAttr *a)
Private Attributes
unsigned char _family
unsigned char _prefixlen
unsigned char _flags
unsigned char _scope
int _index
attrs_t _attrs
Member Typedef Documentation
typedef std::list<NLAddrAttr*> olsr::sys::netlink::NLDelAddr::attrs_t
Constructor & Destructor Documentation
olsr::sys::netlink::NLDelAddr::NLDelAddr (unsigned char f, unsigned char p, unsigned char fl, unsigned char s, int i) [inline]
virtual olsr::sys::netlink::NLDelAddr::~NLDelAddr () [inline, virtual]
References _attrs.
Member Function Documentation
virtual void olsr::sys::netlink::NLDelAddr::accept (Visitor & v) const [inline, virtual]
Implements olsr::sys::netlink::NLMessage.
unsigned char olsr::sys::netlink::NLDelAddr::family () const [inline]
References _family.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
unsigned char olsr::sys::netlink::NLDelAddr::prefixlen () const [inline]
References _prefixlen.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
unsigned char olsr::sys::netlink::NLDelAddr::flags () const [inline]
References _flags.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
unsigned char olsr::sys::netlink::NLDelAddr::scope () const [inline]
References _scope.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
int olsr::sys::netlink::NLDelAddr::index () const [inline]
References _index.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
const attrs_t& olsr::sys::netlink::NLDelAddr::attrs () const [inline]
References _attrs.
Referenced by olsr::sys::netlink::RequestVisitor::visit().
void olsr::sys::netlink::NLDelAddr::add_attr (NLAddrAttr * a) [inline]
References _attrs.
Member Data Documentation
unsigned char olsr::sys::netlink::NLDelAddr::_family [private]
Referenced by family().
unsigned char olsr::sys::netlink::NLDelAddr::_prefixlen [private]
Referenced by prefixlen().
unsigned char olsr::sys::netlink::NLDelAddr::_flags [private]
Referenced by flags().
unsigned char olsr::sys::netlink::NLDelAddr::_scope [private]
Referenced by scope().
int olsr::sys::netlink::NLDelAddr::_index [private]
Referenced by index().
attrs_t olsr::sys::netlink::NLDelAddr::_attrs [private]
Referenced by add_attr(), attrs(), and ~NLDelAddr().
The documentation for this class was generated from the following file:
netlink.hh