Qolyester daemon: olsr::sys::netlink::NLAddrAttrBroadcast Class Reference
olsr::sys::netlink::NLAddrAttrBroadcast Class Reference
#include <netlink.hh>
Public Member Functions
NLAddrAttrBroadcast (const unsigned char *b, unsigned len)
virtual ~NLAddrAttrBroadcast ()
virtual void accept (Visitor &v) const
const unsigned char * bytes () const
unsigned length () const
Private Attributes
unsigned char * _bytes
unsigned _len
Constructor & Destructor Documentation
olsr::sys::netlink::NLAddrAttrBroadcast::NLAddrAttrBroadcast (const unsigned char * b, unsigned len) [inline]
References _bytes.
virtual olsr::sys::netlink::NLAddrAttrBroadcast::~NLAddrAttrBroadcast () [inline, virtual]
References _bytes.
Member Function Documentation
virtual void olsr::sys::netlink::NLAddrAttrBroadcast::accept (Visitor & v) const [inline, virtual]
Implements olsr::sys::netlink::NLAddrAttr.
const unsigned char* olsr::sys::netlink::NLAddrAttrBroadcast::bytes () const [inline]
References _bytes.
Referenced by olsr::sys::netlink::RequestVisitor::visit(), and olsr::sys::netlink::InitVisitor::visit().
unsigned olsr::sys::netlink::NLAddrAttrBroadcast::length () const [inline]
References _len.
Referenced by olsr::sys::netlink::RequestVisitor::visit(), and olsr::sys::netlink::InitVisitor::visit().
Member Data Documentation
unsigned char* olsr::sys::netlink::NLAddrAttrBroadcast::_bytes [private]
Referenced by bytes(), NLAddrAttrBroadcast(), and ~NLAddrAttrBroadcast().
unsigned olsr::sys::netlink::NLAddrAttrBroadcast::_len [private]
Referenced by length().
The documentation for this class was generated from the following file:
netlink.hh