Qolyester daemon: olsr::sys::internal::RoutingSocket Class Reference
olsr::sys::internal::RoutingSocket Class Reference
#include <routingsocket.hh>
Public Member Functions
void print_kernel_routes ()
void remove_old_routes ()
void add_local_route (const address_t &d, unsigned p, const sys::RealInterfaceInfo &i)
void add_remote_route (const address_t &d, unsigned p, const address_t &n)
void remove_local_route (const address_t &d, unsigned p, const sys::RealInterfaceInfo &i)
void remove_remote_route (const address_t &d, unsigned p, const address_t &n)
void add_addr (unsigned i, const InterfaceAddress &a)
void del_addr (unsigned i, const InterfaceAddress &a)
Private Attributes
netlink::NLSocket _s
Member Function Documentation
void olsr::sys::internal::RoutingSocket::print_kernel_routes ()
References _s, olsr::debug, olsr::utl::down(), olsr::net::IPv6Address::family, olsr::sys::netlink::NLSocket::receive(), olsr::sys::netlink::NLSocket::send(), and olsr::utl::up().
Referenced by olsr::sys::RoutingActions::print_kernel_routes().
void olsr::sys::internal::RoutingSocket::remove_old_routes ()
References _s, olsr::net::IPv6Address::family, olsr::sys::netlink::NLSocket::receive(), RTPROT_OLSR, and olsr::sys::netlink::NLSocket::send().
Referenced by olsr::sys::RoutingActions::remove_old_routes().
void olsr::sys::internal::RoutingSocket::add_local_route (const address_t & d, unsigned p, const sys::RealInterfaceInfo & i)
References _s, ADDRESS_SIZE, olsr::net::IPv6Address::bytes(), olsr::net::IPv6Address::family, olsr::sys::RealInterfaceInfo::index(), olsr::sys::RealInterfaceInfo::name(), olsr::sys::netlink::NLSocket::receive(), RTPROT_OLSR, olsr::sys::netlink::NLSocket::send(), and olsr::net::IPv6Address::to_string().
Referenced by olsr::sys::RoutingActions::add_local_route().
void olsr::sys::internal::RoutingSocket::add_remote_route (const address_t & d, unsigned p, const address_t & n)
References _s, ADDRESS_SIZE, olsr::net::IPv6Address::bytes(), olsr::net::IPv6Address::family, olsr::sys::netlink::NLSocket::receive(), RTPROT_OLSR, olsr::sys::netlink::NLSocket::send(), and olsr::net::IPv6Address::to_string().
Referenced by olsr::sys::RoutingActions::add_remote_route().
void olsr::sys::internal::RoutingSocket::remove_local_route (const address_t & d, unsigned p, const sys::RealInterfaceInfo & i)
References _s, ADDRESS_SIZE, olsr::net::IPv6Address::bytes(), olsr::net::IPv6Address::family, olsr::sys::RealInterfaceInfo::index(), olsr::sys::RealInterfaceInfo::name(), olsr::sys::netlink::NLSocket::receive(), RTPROT_OLSR, olsr::sys::netlink::NLSocket::send(), and olsr::net::IPv6Address::to_string().
Referenced by olsr::sys::RoutingActions::remove_local_route().
void olsr::sys::internal::RoutingSocket::remove_remote_route (const address_t & d, unsigned p, const address_t & n)
References _s, ADDRESS_SIZE, olsr::net::IPv6Address::bytes(), olsr::net::IPv6Address::family, olsr::sys::netlink::NLSocket::receive(), RTPROT_OLSR, olsr::sys::netlink::NLSocket::send(), and olsr::net::IPv6Address::to_string().
Referenced by olsr::sys::RoutingActions::remove_remote_route().
void olsr::sys::internal::RoutingSocket::add_addr (unsigned i, const InterfaceAddress & a)
References _s, olsr::sys::internal::InterfaceAddress::address(), ADDRESS_SIZE, olsr::sys::internal::InterfaceAddress::broadcast(), olsr::net::IPv6Address::bytes(), olsr::net::IPv6Address::family, olsr::sys::internal::InterfaceAddress::prefix(), olsr::sys::netlink::NLSocket::receive(), olsr::sys::internal::InterfaceAddress::scope(), and olsr::sys::netlink::NLSocket::send().
void olsr::sys::internal::RoutingSocket::del_addr (unsigned i, const InterfaceAddress & a)
References _s, olsr::sys::internal::InterfaceAddress::address(), ADDRESS_SIZE, olsr::sys::internal::InterfaceAddress::broadcast(), olsr::net::IPv6Address::bytes(), olsr::net::IPv6Address::family, olsr::sys::internal::InterfaceAddress::prefix(), olsr::sys::netlink::NLSocket::receive(), olsr::sys::internal::InterfaceAddress::scope(), and olsr::sys::netlink::NLSocket::send().
Member Data Documentation
netlink::NLSocket olsr::sys::internal::RoutingSocket::_s [private]
Referenced by add_addr(), add_local_route(), add_remote_route(), del_addr(), print_kernel_routes(), remove_local_route(), remove_old_routes(), and remove_remote_route().
The documentation for this class was generated from the following files:
linux/routingsocket.hh
linux/routingsocket.hxx