Qolyester daemon: olsr::utl::Set< Elem, Iset, Iter, CIter > Class Template Reference
olsr::utl::Set< Elem, Iset, Iter, CIter > Class Template Reference
Simple generic set.
#include <set.hh>
Public Types
typedef CIter const_iterator
typedef Iter iterator
Public Member Functions
Set ()
iterator begin ()
iterator end ()
iterator find (const Elem &e)
const_iterator begin () const
const_iterator end () const
const_iterator find (const Elem &e) const
std::pair< iterator, bool > insert (const Elem &e)
template<class InputIterator>
void insert (InputIterator f, InputIterator l)
void erase (iterator pos)
void erase (const Elem &e)
bool empty () const
set_t::size_type size () const
bool operator[] (const Elem &e) const
This & operator|= (const This &rhs)
This operator| (const This &rhs) const
This & operator-= (const This &rhs)
This operator- (const This &rhs) const
This & operator &= (const This &rhs)
This operator & (const This &rhs) const
Private Types
typedef Set< Elem, Iset, Iter,
CIter > This
typedef Iset set_t
Private Attributes
set_t set_
Friends
class sch::StatePrinter
Detailed Description
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator>
class olsr::utl::Set< Elem, Iset, Iter, CIter >
Simple generic set.
Parameters:
Elem element class
Iset implementation set class
Iter mutable iterator on implementation set, defaults to Iset::iterator
CIter immutable iterator on implementation set, defaults to Iset::const_iterator
Member Typedef Documentation
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> typedef Set<Elem, Iset, Iter, CIter> olsr::utl::Set< Elem, Iset, Iter, CIter >::This [private]
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> typedef Iset olsr::utl::Set< Elem, Iset, Iter, CIter >::set_t [private]
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> typedef CIter olsr::utl::Set< Elem, Iset, Iter, CIter >::const_iterator
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> typedef Iter olsr::utl::Set< Elem, Iset, Iter, CIter >::iterator
Constructor & Destructor Documentation
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> olsr::utl::Set< Elem, Iset, Iter, CIter >::Set () [inline]
Member Function Documentation
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> iterator olsr::utl::Set< Elem, Iset, Iter, CIter >::begin () [inline]
Begining of the set.
Returns:
iterator on the first element
References olsr::utl::Set< Elem, Iset, Iter, CIter >::set_.
Referenced by olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::add_key(), olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::begin(), olsr::utl::Subset< MultiAdapt< Set >, Action, Predicate, ActionSet >::begin(), olsr::utl::Subset< utl::MultiAdapt< utl::Index< std::multiset, std::set< ulink_t >, ilinkless > >, olsr::utl::NoAction< olsr::set::Neighbor, lset_t::iterator >, olsr::set::Neighbor::lset_valid, olsr::set::Neighbor >::begin(), olsr::gra::AdjGraph::build_asetmap(), olsr::alg::compute_routes(), olsr::utl::Index< std::multiset, Set, Comp >::equal_range(), olsr::utl::Index< std::set, Set, Comp >::find(), olsr::alg::flush_routes(), olsr::utl::Set< Elem, Iset, Iter, CIter >::operator &=(), olsr::operator*(), olsr::operator-(), olsr::utl::Set< Elem, Iset, Iter, CIter >::operator-=(), olsr::utl::Set< Elem, Iset, Iter, CIter >::operator|=(), and olsr::gra::AdjGraph::to_string().
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> iterator olsr::utl::Set< Elem, Iset, Iter, CIter >::end () [inline]
End of the set.
Returns:
iterator past the last element
References olsr::utl::Set< Elem, Iset, Iter, CIter >::set_.
Referenced by olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::act(), olsr::utl::MSIndex< std::set< ulink_t >, 0, olsr::net::IPv6Address >::add_key(), olsr::gra::AdjGraph::build_asetmap(), olsr::alg::compute_routes(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::destroy(), olsr::utl::Subset< MSAdapt< Set >, Action, Predicate, ActionSet >::end(), olsr::utl::Subset< MultiAdapt< Set >, Action, Predicate, ActionSet >::end(), olsr::utl::Subset< utl::MultiAdapt< utl::Index< std::multiset, std::set< ulink_t >, ilinkless > >, olsr::utl::NoAction< olsr::set::Neighbor, lset_t::iterator >, olsr::set::Neighbor::lset_valid, olsr::set::Neighbor >::end(), olsr::alg::flush_routes(), olsr::gra::AdjGraph::insert_arc(), olsr::utl::MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >::is_valid(), olsr::utl::MaskIterator< Set, Action, Predicate, ActionSet >::is_valid(), olsr::utl::Set< Elem, Iset, Iter, CIter >::operator &=(), olsr::operator*(), olsr::operator-(), olsr::utl::Set< Elem, Iset, Iter, CIter >::operator-=(), olsr::utl::Set< Elem, Iset, Iter, CIter >::operator[](), olsr::utl::Set< Elem, Iset, Iter, CIter >::operator|=(), olsr::gra::AdjGraph::remove_arc(), olsr::gra::AdjGraph::remove_arc_then_node(), olsr::gra::AdjGraph::remove_node(), olsr::gra::AdjGraph::remove_node_if_alone(), and olsr::gra::AdjGraph::to_string().
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> iterator olsr::utl::Set< Elem, Iset, Iter, CIter >::find (const Elem & e) [inline]
Find a given element in the set.
e reference to the element to find
Returns:
iterator on the element or past the end if not found.
References olsr::utl::Set< Elem, Iset, Iter, CIter >::set_.
Referenced by olsr::gra::AdjGraph::build_asetmap(), olsr::alg::compute_routes(), olsr::utl::Subset< utl::MultiAdapt< utl::Index< std::multiset, std::set< ulink_t >, ilinkless > >, olsr::utl::NoAction< olsr::set::Neighbor, lset_t::iterator >, olsr::set::Neighbor::lset_valid, olsr::set::Neighbor >::find(), olsr::gra::AdjGraph::insert_arc(), olsr::operator*(), olsr::operator-(), olsr::utl::Set< Elem, Iset, Iter, CIter >::operator[](), olsr::gra::AdjGraph::remove_arc(), olsr::gra::AdjGraph::remove_arc_then_node(), olsr::gra::AdjGraph::remove_node(), and olsr::gra::AdjGraph::remove_node_if_alone().
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> const_iterator olsr::utl::Set< Elem, Iset, Iter, CIter >::begin () const [inline]
Begining of the set.
Returns:
const iterator on the first element
References olsr::utl::Set< Elem, Iset, Iter, CIter >::set_.
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> const_iterator olsr::utl::Set< Elem, Iset, Iter, CIter >::end () const [inline]
End of the set.
Returns:
const iterator past the last element
References olsr::utl::Set< Elem, Iset, Iter, CIter >::set_.
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> const_iterator olsr::utl::Set< Elem, Iset, Iter, CIter >::find (const Elem & e) const [inline]
Find a given element in the set.
e reference to the element to find
Returns:
const iterator on the element or past the end if not found.
References olsr::utl::Set< Elem, Iset, Iter, CIter >::set_.
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> std::pair<iterator, bool> olsr::utl::Set< Elem, Iset, Iter, CIter >::insert (const Elem & e) [inline]
Element insertion method.
e reference to the element to insert
Returns:
pair of iterator on the inserted element and bool indicating whether the element was actually inserted.
References olsr::utl::Set< Elem, Iset, Iter, CIter >::set_.
Referenced by olsr::alg::compute_routes(), olsr::alg::dijkstra(), olsr::utl::Index< std::multiset, Set, Comp >::equal_range(), olsr::utl::Index< std::set, Set, Comp >::find(), olsr::gra::AdjGraph::insert_arc(), olsr::gra::AdjGraph::insert_node(), olsr::operator*(), olsr::operator-(), and olsr::utl::Set< Elem, Iset, Iter, CIter >::operator|=().
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> template<class InputIterator> void olsr::utl::Set< Elem, Iset, Iter, CIter >::insert (InputIterator f, InputIterator l) [inline]
Element range insertion method.
References olsr::utl::Set< Elem, Iset, Iter, CIter >::set_.
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> void olsr::utl::Set< Elem, Iset, Iter, CIter >::erase (iterator pos) [inline]
Element removal method.
pos iterator on the element to remove
References olsr::utl::Set< Elem, Iset, Iter, CIter >::set_.
Referenced by olsr::utl::Set< Elem, Iset, Iter, CIter >::operator &=(), olsr::utl::Set< Elem, Iset, Iter, CIter >::operator-=(), olsr::gra::AdjGraph::remove_arc(), and olsr::gra::AdjGraph::remove_node().
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> void olsr::utl::Set< Elem, Iset, Iter, CIter >::erase (const Elem & e) [inline]
Element removal method.
e reference to the element to remove
References olsr::utl::Set< Elem, Iset, Iter, CIter >::set_.
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> bool olsr::utl::Set< Elem, Iset, Iter, CIter >::empty () const [inline]
Empty predicate method.
Returns:
true if the set is empty
References olsr::utl::Set< Elem, Iset, Iter, CIter >::set_.
Referenced by olsr::gra::AdjGraph::to_string().
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> set_t::size_type olsr::utl::Set< Elem, Iset, Iter, CIter >::size () const [inline]
References olsr::utl::Set< Elem, Iset, Iter, CIter >::set_.
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> bool olsr::utl::Set< Elem, Iset, Iter, CIter >::operator[] (const Elem & e) const [inline]
Hold
References olsr::utl::Set< Elem, Iset, Iter, CIter >::end(), and olsr::utl::Set< Elem, Iset, Iter, CIter >::find().
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> This& olsr::utl::Set< Elem, Iset, Iter, CIter >::operator|= (const This & rhs) [inline]
References olsr::utl::Set< Elem, Iset, Iter, CIter >::begin(), olsr::utl::Set< Elem, Iset, Iter, CIter >::end(), and olsr::utl::Set< Elem, Iset, Iter, CIter >::insert().
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> This olsr::utl::Set< Elem, Iset, Iter, CIter >::operator| (const This & rhs) const [inline]
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> This& olsr::utl::Set< Elem, Iset, Iter, CIter >::operator-= (const This & rhs) [inline]
References olsr::utl::Set< Elem, Iset, Iter, CIter >::begin(), olsr::utl::Set< Elem, Iset, Iter, CIter >::end(), and olsr::utl::Set< Elem, Iset, Iter, CIter >::erase().
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> This olsr::utl::Set< Elem, Iset, Iter, CIter >::operator- (const This & rhs) const [inline]
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> This& olsr::utl::Set< Elem, Iset, Iter, CIter >::operator &= (const This & rhs) [inline]
References olsr::utl::Set< Elem, Iset, Iter, CIter >::begin(), olsr::utl::Set< Elem, Iset, Iter, CIter >::end(), and olsr::utl::Set< Elem, Iset, Iter, CIter >::erase().
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> This olsr::utl::Set< Elem, Iset, Iter, CIter >::operator & (const This & rhs) const [inline]
Friends And Related Function Documentation
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> friend class sch::StatePrinter [friend]
Member Data Documentation
template<class Elem, class Iset, class Iter = typename Iset::iterator, class CIter = typename Iset::const_iterator> set_t olsr::utl::Set< Elem, Iset, Iter, CIter >::set_ [private]
Referenced by olsr::utl::Set< Elem, Iset, Iter, CIter >::begin(), olsr::utl::Set< Elem, Iset, Iter, CIter >::empty(), olsr::utl::Set< Elem, Iset, Iter, CIter >::end(), olsr::utl::Set< Elem, Iset, Iter, CIter >::erase(), olsr::utl::Set< Elem, Iset, Iter, CIter >::find(), olsr::sch::StatePrinter::handle(), olsr::utl::Set< Elem, Iset, Iter, CIter >::insert(), and olsr::utl::Set< Elem, Iset, Iter, CIter >::size().
The documentation for this class was generated from the following file:
set.hh