Qolyester daemon: olsr::sch::internal::PollData Struct Reference
olsr::sch::internal::PollData Struct Reference
#include <scheduler.hh>
Public Member Functions
PollData (int fd, short events)
bool active () const
bool operator< (const PollData &rhs) const
Static Public Member Functions
template<class C, class A>
static void poll (std::multiset< IOEvent *, C, A > &s, int timeout=-1)
Public Attributes
::pollfd pfd
Static Private Member Functions
static int priority (const ::pollfd &ufd)
Constructor & Destructor Documentation
olsr::sch::internal::PollData::PollData (int fd, short events) [inline]
References pfd.
Member Function Documentation
bool olsr::sch::internal::PollData::active () const [inline]
References pfd.
Referenced by operator<().
bool olsr::sch::internal::PollData::operator< (const PollData & rhs) const [inline]
References active(), pfd, and priority().
template<class C, class A> void olsr::sch::internal::PollData::poll (std::multiset< IOEvent *, C, A > & s, int timeout = -1) [inline, static]
References olsr::error, olsr::sch::PollEvent_< P >::p(), and pfd.
static int olsr::sch::internal::PollData::priority (const ::pollfd & ufd) [inline, static, private]
Referenced by operator<().
Member Data Documentation
::pollfd olsr::sch::internal::PollData::pfd
Referenced by active(), operator<(), poll(), and PollData().
The documentation for this struct was generated from the following files:
scheduler.hh
scheduler.hxx