Qolyester daemon: olsr::sch::QolyesterLoopHandler Class Reference
olsr::sch::QolyesterLoopHandler Class Reference
#include <events.hh>
Public Member Functions
virtual bool operator() () const
Private Types
typedef QolyesterLoopHandler This
typedef LoopHandler Super
Member Typedef Documentation
typedef QolyesterLoopHandler olsr::sch::QolyesterLoopHandler::This [private]
typedef LoopHandler olsr::sch::QolyesterLoopHandler::Super [private]
Member Function Documentation
bool olsr::sch::QolyesterLoopHandler::operator() () const [inline, virtual]
Reimplemented from olsr::sch::LoopHandler.
References olsr::advset_changed, olsr::alg::compute_routes(), olsr::sch::Scheduler::erase(), olsr::iface_set, olsr::utl::TimeVal::in(), olsr::sch::Scheduler::insert(), olsr::utl::TimeVal::jitter(), olsr::utl::Mark::mark(), olsr::cst::maxjitter, olsr::alg::mprselection(), olsr::mprset_recomp, olsr::sch::LoopHandler::operator()(), olsr::pending_messages, olsr::sch::remove_routes(), olsr::utl::Mark::reset(), olsr::routes_recomp, olsr::scheduler, olsr::set::InterfaceSet::send_messages(), olsr::sch::TimedEvent::set_next(), olsr::tc_sender, olsr::terminate_now, and olsr::warning.
The documentation for this class was generated from the following files:
events.hh
events.hxx