Qolyester daemon: olsr::sch::PacketReceiver Class Reference
olsr::sch::PacketReceiver Class Reference
#include <events.hh>
Public Member Functions
PacketReceiver (iface_t *i)
virtual void handle ()
Private Types
typedef PacketReceiver This
typedef IOEvent Super
Private Attributes
iface_t * iface_
Member Typedef Documentation
typedef PacketReceiver olsr::sch::PacketReceiver::This [private]
Reimplemented from olsr::sch::PollEvent_< P >.
typedef IOEvent olsr::sch::PacketReceiver::Super [private]
Reimplemented from olsr::sch::PollEvent_< P >.
Constructor & Destructor Documentation
olsr::sch::PacketReceiver::PacketReceiver (iface_t * i) [inline]
References olsr::net::RealInterface::insert_event().
Member Function Documentation
void olsr::sch::PacketReceiver::handle () [inline, virtual]
Virtual handling method.
Implements olsr::sch::Event.
References olsr::net::RealInterface::addr(), olsr::pkt::Packet::data(), iface_, olsr::sch::Scheduler::insert(), olsr::sch::PollEvent_< P >::p(), olsr::pkt::Packet::parse(), olsr::net::RealInterface::receive(), olsr::scheduler, olsr::pkt::Packet::sender(), and olsr::warning.
Member Data Documentation
iface_t* olsr::sch::PacketReceiver::iface_ [private]
Referenced by handle().
The documentation for this class was generated from the following files:
events.hh
events.hxx