Qolyester daemon: olsr::set::TopologySet Class Reference
olsr::set::TopologySet Class Reference
#include <topology.hh>
Public Types
typedef val_tset_t toposet_t
Public Member Functions
toposet_t & toposet ()
TopologySet ()
void insert (const TopologyEntry &x)
void erase (const tset_t::iterator &pos)
Private Types
typedef TopologySet This
typedef sch::Updatable
< TopologyEntry > elem_t
typedef std::multiset< elem_t > tset_t
typedef sch::upd::SetEraser
< This, tset_t::iterator > eraser_t
typedef sch::UpdateEvent
< eraser_t > updater_t
typedef utl::Subset
< utl::MultiAdapt< tset_t >
, utl::NoAction< This,
tset_t::iterator >
, utl::DefaultPredicate< This,
tset_t::iterator >, This > val_tset_t
Private Attributes
tset_t tset_
toposet_t toposet_
Friends
class sch::StatePrinter
Member Typedef Documentation
typedef TopologySet olsr::set::TopologySet::This [private]
typedef sch::Updatable<TopologyEntry> olsr::set::TopologySet::elem_t [private]
typedef std::multiset<elem_t> olsr::set::TopologySet::tset_t [private]
typedef sch::upd::SetEraser<This, tset_t::iterator> olsr::set::TopologySet::eraser_t [private]
typedef sch::UpdateEvent<eraser_t> olsr::set::TopologySet::updater_t [private]
typedef utl::Subset<utl::MultiAdapt<tset_t>, utl::NoAction<This, tset_t::iterator>, utl::DefaultPredicate<This, tset_t::iterator>, This> olsr::set::TopologySet::val_tset_t [private]
typedef val_tset_t olsr::set::TopologySet::toposet_t
Constructor & Destructor Documentation
olsr::set::TopologySet::TopologySet () [inline]
Member Function Documentation
toposet_t& olsr::set::TopologySet::toposet () [inline]
References toposet_.
Referenced by olsr::msg::TCMessage::parse().
void olsr::set::TopologySet::insert (const TopologyEntry & x) [inline]
References olsr::set::TopologyEntry::dest_addr(), olsr::sch::Scheduler::insert(), olsr::gra::AdjGraph::insert_arc(), olsr::gra::AdjGraph::insert_node(), olsr::set::TopologyEntry::last_addr(), olsr::path_net, olsr::routes_recomp, olsr::scheduler, olsr::utl::Mark::set_mark(), olsr::set::TopologyEntry::time(), olsr::gra::topo, and tset_.
Referenced by olsr::msg::TCMessage::parse().
void olsr::set::TopologySet::erase (const tset_t::iterator & pos) [inline]
References olsr::cproxy, olsr::sch::Scheduler::destroy(), olsr::gra::AdjNode::make_key(), olsr::set::Neighbor::make_key(), olsr::gra::AdjInfo::make_key(), olsr::path_net, olsr::gra::AdjGraph::remove_arc(), olsr::gra::AdjGraph::remove_node_if_alone(), olsr::routes_recomp, olsr::scheduler, olsr::utl::Mark::set_mark(), olsr::set::CoherenceProxy::sym_neighborset(), olsr::gra::topo, and tset_.
Referenced by olsr::msg::TCMessage::parse().
Friends And Related Function Documentation
friend class sch::StatePrinter [friend]
Member Data Documentation
tset_t olsr::set::TopologySet::tset_ [private]
Referenced by erase(), olsr::sch::StatePrinter::handle(), and insert().
toposet_t olsr::set::TopologySet::toposet_ [private]
Referenced by toposet().
The documentation for this class was generated from the following files:
topology.hh
topology.hxx