Qolyester daemon: olsr::sch Namespace Reference
olsr::sch Namespace Reference
Classes
class MessageSender
class MessageSender< msg::TCMessage >
class MessageForwarder
class StatePrinter
class PacketSender
class PacketReceiver
class QolyesterLoopHandler
class LoopHandler
class Event
Abstract event class.
class TimedEvent
Timed event abstract class.
class UpdateEvent
class PeriodicEvent_
class JitteredEvent
class PollEvent_
class Scheduler
The scheduler class.
class Updatable
Namespaces
namespace internal
namespace upd
Typedefs
typedef PeriodicEvent_ PeriodicEvent
typedef PollEvent_
< internal::PollData > IOEvent
Functions
void remove_routes ()
void term_handler (int)
Termination signals handler function.
void int_handler (int)
void quit_handler (int)
Typedef Documentation
typedef PollEvent_ olsr::sch::IOEvent
typedef PeriodicEvent_ olsr::sch::PeriodicEvent
Function Documentation
void olsr::sch::int_handler (int)
References olsr::utl::Mark::set_mark(), and olsr::terminate_now.
void olsr::sch::quit_handler (int)
void olsr::sch::remove_routes () [inline]
References olsr::debug, and olsr::alg::flush_routes().
Referenced by main(), and olsr::sch::QolyesterLoopHandler::operator()().
void olsr::sch::term_handler (int)
Termination signals handler function.
References olsr::utl::Mark::set_mark(), and olsr::terminate_now.