Qolyester daemon: main.cc File Reference
main.cc File Reference
As its name suggests, this is the file that contains the main function. =).
#include "config.hh"
#include "sch/scheduler.hh"
#include "sch/events.hh"
#include "utl/args.hh"
#include "utl/syslog.hh"
#include "cst/params.hcc"
#include "utl/log.hcc"
#include "daemon_static_members_init.hcc"
#include "static_members_init.hcc"
#include "gra/graph.hcc"
#include "set/duplicate.hcc"
#include "set/gate.hcc"
#include "set/hna.hcc"
#include "set/interfaces.hcc"
#include "set/mid.hcc"
#include "set/neighbors.hcc"
#include "set/routes.hcc"
#include "set/topology.hcc"
Namespaces
namespace olsr
Functions
std::ostream olsr::dump_state (dump.rdbuf())
std::ostream olsr::dump_prof (dump.rdbuf())
std::ostream olsr::dump_hello (dump.rdbuf())
std::ostream olsr::dump_tc (dump.rdbuf())
std::ostream olsr::dump_mid (dump.rdbuf())
std::ostream olsr::dump_hna (dump.rdbuf())
int main (int argc, char *argv[])
Variables
sched_t scheduler * olsr::new
utl::Mark olsr::terminate_now
utl::Mark olsr::mprset_recomp
const std::string olsr::progname = "Qolyester"
const std::string olsr::shortname = "qolsrd"
const std::string olsr::version = VERSION
sch::TimedEvent * olsr::hello_sender = 0
sch::TimedEvent * olsr::tc_sender = 0
sch::TimedEvent * olsr::mid_sender = 0
sch::TimedEvent * olsr::hna_sender = 0
sch::TimedEvent * olsr::state_printer = 0
Detailed Description
As its name suggests, this is the file that contains the main function. =).
Author:
Ignacy Gawedzki
Date:
Thu Sep 25 20:37:50 2003
Function Documentation
int main (int argc, char * argv[])
This is the main function.
argc command line argument count.
argv command line argument vector.
Returns:
0 for normal termination, 1 for error.
References olsr::set::GateSet::begin(), olsr::set::InterfaceSet::begin(), olsr::alg::clean_routes(), olsr::utl::deindent(), olsr::do_dump_state, olsr::utl::down(), olsr::dump, olsr::set::GateSet::empty(), olsr::set::InterfaceSet::empty(), olsr::set::GateSet::end(), olsr::set::InterfaceSet::end(), olsr::error, olsr::gate_set, olsr::utl::ErrnoException::get_errno(), olsr::hello_sender, olsr::hna_sender, olsr::iface_set, indent, olsr::sch::Scheduler::insert(), olsr::sch::Scheduler::loop(), olsr::main_addr, olsr::mid_sender, olsr::nodetach, olsr::utl::output_syslog(), olsr::utl::parse_args(), olsr::progname, olsr::sch::remove_routes(), olsr::scheduler, olsr::set::InterfaceSet::size(), olsr::utl::start_output(), olsr::state_printer, olsr::tc_sender, olsr::utl::up(), and olsr::use_syslog.