Qolyester daemon: olsr::utl Namespace Reference
olsr::utl Namespace Reference
Classes
struct pless
struct pequal_to
struct iless
struct iequal_to
struct Data_
Base class for Data and ConstData.
struct Data
struct ConstData
class ErrnoException
struct DefaultPredicate
struct NoAction
struct type_traits
struct type_traits< const T >
struct type_traits< T & >
struct type_traits< T * >
class DeconstIterator
class DerefIterator
class KeyedIterator
class MaskIterator
class MaskIterator< MSAdapt< Set >, Action, Predicate, ActionSet >
struct of
class LevelableBuf
class PrefixBuf
struct StringPrefixer
struct Timestamper
struct basic_indent_
class basic_dummyostream
class basic_ybuf
class basic_levelbuf
class basic_dummybuf
struct up_
struct down_
class Mark
class NullType
class Seqnum
Sequence number class.
class Set
Simple generic set.
struct index_traits< S< K, C, A > >
class Index< std::set, Set, Comp >
class Index< std::multiset, Set, Comp >
class MSIndex
class Subset
class Subset< MultiAdapt< Set >, Action, Predicate, ActionSet >
class Subset< MSAdapt< Set >, Action, Predicate, ActionSet >
class Stampable
class MultiStampable
class MultiStampable< 1, Key, Compare >
struct imultistampable_less
struct multistampable_less
struct multistampable_less< 0, Key, Compare >
struct multistampable_less< 1, Key, Compare >
class SyslogBuf
class TimeVal
Proxy class for the timeval standard C data structure.
class Vtime
Validity time processing and calculation.
Namespaces
namespace internal
Functions
void parse_args (int &argc, char **&argv)
void output_syslog ()
void start_output ()
void stop_output ()
std::ostream & operator<< (std::ostream &os, const of &f)
template<class C, class T>
std::basic_ostream< C, T > & indent (std::basic_ostream< C, T > &os)
template<class C, class T>
std::basic_ostream< C, T > & deindent (std::basic_ostream< C, T > &os)
template<typename C, typename T>
basic_indent_< C, T > basic_indent (const std::basic_string< C, T > &s=std::basic_string< C, T >(2, ' '))
template<typename C, typename T>
std::basic_ostream< C, T > & operator<< (std::basic_ostream< C, T > &os, const basic_indent_< C, T > &i)
template<typename C, typename T>
std::basic_ostream< C, T > & up (std::basic_ostream< C, T > &os)
template<typename C, typename T>
std::basic_ostream< C, T > & down (std::basic_ostream< C, T > &os)
template<typename C, typename T>
std::basic_ostream< C, T > & reset (std::basic_ostream< C, T > &os)
up_ up (unsigned i=1)
down_ down (unsigned i=1)
template<typename C, typename T>
std::basic_ostream< C, T > & operator<< (std::basic_ostream< C, T > &os, const up_ &u)
template<typename C, typename T>
std::basic_ostream< C, T > & operator<< (std::basic_ostream< C, T > &os, const down_ &d)
std::ostream & operator<< (std::ostream &, const NullType &)
std::ostream & operator<< (std::ostream &, const TimeVal &)
std::ostream & operator<< (std::ostream &, const Vtime &)
Variables
char cerr_buffer [4096]
Function Documentation
template<typename C, typename T> basic_indent_<C, T> olsr::utl::basic_indent (const std::basic_string< C, T > & s = std::basic_string<C, T>(2, ' ')) [inline]
References olsr::utl::basic_indent_< C, T >::s.
template<class C, class T> std::basic_ostream<C, T>& olsr::utl::deindent (std::basic_ostream< C, T > & os) [inline]
Referenced by olsr::msg::HELLOMessage::dump(), olsr::sch::StatePrinter::handle(), olsr::sch::Scheduler::handle_ioevents(), olsr::sch::Scheduler::handle_tevents(), and main().
down_ olsr::utl::down (unsigned i = 1) [inline]
References olsr::utl::down_::i.
Referenced by olsr::msg::HELLOMessage::dump(), olsr::sch::Scheduler::erase(), olsr::sch::PacketSender::handle(), olsr::sch::StatePrinter::handle(), olsr::sch::Scheduler::handle_ioevents(), olsr::sch::Scheduler::handle_tevents(), olsr::sch::Scheduler::insert(), main(), olsr::set::upd::LinkUpdater::operator()(), olsr::sys::internal::RoutingSocket::print_kernel_routes(), olsr::sch::PacketSender::push_packet(), and olsr::net::RealInterface::shipout().
template<typename C, typename T> std::basic_ostream<C, T>& olsr::utl::down (std::basic_ostream< C, T > & os) [inline]
References olsr::utl::LevelableBuf::decrease_level().
Referenced by parse_args().
template<class C, class T> std::basic_ostream<C, T>& olsr::utl::indent (std::basic_ostream< C, T > & os) [inline]
std::ostream & olsr::utl::operator<< (std::ostream & o, const Vtime & v) [inline]
References olsr::utl::Vtime::output().
std::ostream & olsr::utl::operator<< (std::ostream & o, const TimeVal & t) [inline]
std::ostream & olsr::utl::operator<< (std::ostream & os, const NullType &) [inline]
template<typename C, typename T> std::basic_ostream<C, T>& olsr::utl::operator<< (std::basic_ostream< C, T > & os, const down_ & d) [inline]
References olsr::utl::LevelableBuf::decrease_level().
template<typename C, typename T> std::basic_ostream<C, T>& olsr::utl::operator<< (std::basic_ostream< C, T > & os, const up_ & u) [inline]
References olsr::utl::LevelableBuf::increase_level().
template<typename C, typename T> std::basic_ostream<C, T>& olsr::utl::operator<< (std::basic_ostream< C, T > & os, const basic_indent_< C, T > & i) [inline]
std::ostream& olsr::utl::operator<< (std::ostream & os, const of & f) [inline]
References olsr::utl::of::_f, olsr::utl::of::_p, olsr::utl::of::_val, and olsr::utl::of::_w.
void olsr::utl::output_syslog () [inline]
References olsr::debug, olsr::dump, olsr::error, olsr::notice, PROC_LOG, PROC_LOG_PREFIXED, olsr::shortname, and olsr::warning.
Referenced by main(), and parse_args().
void olsr::utl::parse_args (int & argc, char **& argv) [inline]
References ARG_ALLFILE, ARG_DEBUGFILE, ARG_DEBUGTRACE, ARG_DIRTYPROMISCHACK, ARG_DUMPALL, ARG_DUMPFILE, ARG_DUMPHELLO, ARG_DUMPHNA, ARG_DUMPINTERVAL, ARG_DUMPMID, ARG_DUMPPROF, ARG_DUMPSTATE, ARG_DUMPTC, ARG_DUPHOLDTIME, ARG_ERRORFILE, ARG_HELLOGRACE, ARG_HELLOINTERVAL, ARG_HNAHOLDTIME, ARG_HNAINTERVAL, ARG_HYSTHI, ARG_HYSTLO, ARG_HYSTSCALING, ARG_MAXJITTERTIME, ARG_MIDHOLDTIME, ARG_MIDINTERVAL, ARG_NEIGHBHOLDTIME, ARG_NOTABLES, ARG_NOTICEFILE, ARG_QUEUESIZE, ARG_REFRESHINTERVAL, ARG_SWSOCK, ARG_TCINTERVAL, ARG_TOPHOLDTIME, ARG_VERSION, ARG_WARNINGFILE, olsr::current_log_level, olsr::debug, olsr::debugtrace, olsr::die(), olsr::dirty_promisc_hack, olsr::do_dump_hello, olsr::do_dump_prof, olsr::do_dump_state, olsr::do_dump_tc, down(), olsr::dump, olsr::dump_file, olsr::dump_hello, olsr::dump_hna, olsr::cst::dump_interval, olsr::dump_mid, olsr::dump_prof, olsr::dump_state, olsr::dump_tc, olsr::cst::dup_hold_time, olsr::error, olsr::error_file, olsr::gate_set, GETFLOAT, GETNUMBER, olsr::cst::hello_grace, olsr::cst::hello_interval, olsr::iface_set, olsr::set::GateSet::insert(), olsr::set::InterfaceSet::insert(), olsr::cst::maxjitter, olsr::cst::neighb_hold_time, olsr::net::IPv6Address::network(), olsr::nodetach, olsr::notables, olsr::notice, olsr::notice_file, output_syslog(), PROC_LOG, PROC_LOG_PREFIXED, olsr::putversion(), olsr::cst::queue_size, olsr::cst::refresh_interval, reset(), olsr::cst::tc_interval, olsr::tc_redundancy, olsr::timestamps, olsr::cst::top_hold_time, up(), olsr::usage(), olsr::use_syslog, olsr::warning, olsr::warning_file, WILL_ALWAYS, WILL_DEFAULT, WILL_HIGH, WILL_LOW, WILL_NEVER, and olsr::willingness.
Referenced by main().
template<typename C, typename T> std::basic_ostream<C, T>& olsr::utl::reset (std::basic_ostream< C, T > & os) [inline]
References olsr::utl::LevelableBuf::reset_level().
Referenced by parse_args().
void olsr::utl::start_output () [inline]
References cerr_buffer, olsr::debug, olsr::dump, olsr::dump_hello, olsr::dump_hna, olsr::dump_mid, olsr::dump_prof, olsr::dump_state, olsr::dump_tc, olsr::error, olsr::notice, stop_output(), and olsr::warning.
Referenced by main().
void olsr::utl::stop_output ()
References olsr::debug, olsr::dump, olsr::dump_hello, olsr::dump_hna, olsr::dump_mid, olsr::dump_prof, olsr::dump_state, olsr::dump_tc, olsr::error, olsr::notice, and olsr::warning.
Referenced by start_output().
up_ olsr::utl::up (unsigned i = 1) [inline]
References olsr::utl::up_::i.
Referenced by olsr::msg::HELLOMessage::dump(), olsr::sch::Scheduler::erase(), olsr::sch::PacketSender::handle(), olsr::sch::StatePrinter::handle(), olsr::sch::Scheduler::handle_ioevents(), olsr::sch::Scheduler::handle_tevents(), olsr::sch::Scheduler::insert(), main(), olsr::set::upd::LinkUpdater::operator()(), olsr::sys::internal::RoutingSocket::print_kernel_routes(), olsr::sch::PacketSender::push_packet(), and olsr::net::RealInterface::shipout().
template<typename C, typename T> std::basic_ostream<C, T>& olsr::utl::up (std::basic_ostream< C, T > & os) [inline]
References olsr::utl::LevelableBuf::increase_level().
Referenced by parse_args().
Variable Documentation
char olsr::utl::cerr_buffer[4096] [static]
Referenced by start_output().